### ISSUE TITLE
文章字太小了，在Markdown编写后，加粗的字跟普通的字差距不够大。一眼扫过文章的话，看不出来那些字是加粗的，哪些不是。  1. 请问在那可以改？ 2. 建议后续把Markdown语法里修饰的部分与不加修饰的文章渲染后的视觉差别拉大。

### ISSUE THREAD

**Issue by naichaduck** [XPoet/hexo-theme-keep#101]
一眼扫过文章的话，看不出来那些字是加粗的，哪些不是。

1. 请问在那可以改？
2. 建议后续把Markdown语法里修饰的部分与不加修饰的文章渲染后的视觉差别拉大。

**Comment by XPoet** [comment]
keep主题目前样式都是精心调整过的，你可以修改主题源码的 css 目录下的 markdown.styl 文件来达到自己喜欢的样式
