### ISSUE TITLE
部署到阿里云服务器上，在本地测试能成功，但是部署后页面显示出错。

### ISSUE THREAD

**Issue by liuyunzhuo** [XPoet/hexo-theme-keep#105]
页面网址为：http://116.62.113.0/

**Comment by XPoet** [comment]
本地测试成功，说明 keep 主题能正常使用。部署阿里云不属于 Keep 主题技术范畴，请自行查阅阿里云官方文档或百度/谷歌搜索相关的解决方法，博客也没部署到阿里云，你也没把错误信息贴出来，无法解答。该 Issue 关闭

**Comment by XPoet** [comment]
本地测试成功，说明 keep 主题能正常使用。部署阿里云不属于 Keep 主题技术范畴，请自行查阅阿里云官方文档或百度/谷歌搜索相关的解决方法，博客也没部署到阿里云，你也没把错误信息贴出来，无法解答。该 Issue 关闭
