### ISSUE TITLE
首页文章块底部的时间标签显示undefined

### ISSUE THREAD

**Issue by NekoRectifier** [XPoet/hexo-theme-keep#108]
请问哪些因素会导致该问题出现?
![image](https://user-images.githubusercontent.com/51020139/128202992-aca22441-14ec-4a18-91bc-6ae7c9cc1091.png)

**Comment by XPoet** [comment]
检查一下你的文章 md 文件日期格式是否正确。
请参考 hexo 命令自动生成的日期格式

**Comment by NekoRectifier** [comment]
多谢
