### ISSUE TITLE
最新版本 3.4.3，开启文章侧边栏目录以后下滑后头部导航自动隐藏，然而再上滑就不显示了

### ISSUE THREAD

**Issue by suzhiF** [XPoet/hexo-theme-keep#109]
不知道配置的问题还是什么
![image](https://user-images.githubusercontent.com/46362400/128277091-48be0523-a8be-4ef0-b924-44a836d2ef3d.png)
![image](https://user-images.githubusercontent.com/46362400/128277153-11f2711a-6d83-4db3-a224-0d8c6f651078.png)
![image](https://user-images.githubusercontent.com/46362400/128277198-ce2c9e58-20b4-4e30-8c73-e2ee10f5020e.png)
![image](https://user-images.githubusercontent.com/46362400/128277216-2d9ee915-1009-4019-84a0-743305e42188.png)
导航栏没有了

**Comment by suzhiF** [comment]
![image](https://user-images.githubusercontent.com/46362400/128277328-a25a4b9a-28ff-40ea-aa70-fca266154f8f.png)

**Comment by XPoet** [comment]
这个问题没遇到过。
请提供下：
1、你的网站链接
2、hexo 项目源文件
要不然不好排查
