### ISSUE TITLE
github action自动化部署出现日期undefined

### ISSUE THREAD

**Issue by cemonliu** [XPoet/hexo-theme-keep#115]
github action自动化部署后，主页对于新发布的文章显示创建日期为Undefined

本机调试或者直接deploy上去没问题
![image](https://user-images.githubusercontent.com/42933407/133016419-ac585dc0-9361-47c2-bc4a-ef7bf49d27f1.png)

**Comment by XPoet** [comment]
要么是你文章 md 文件的日期格式有误，要么就是你使用 GitHub Action 在编译环节出问题。
提供下你的文章 md 文件我看看格式对不对

**Comment by cemonliu** [comment]
其他都没写啊，就是默认格式。我发现如果几天前是正常的，分钟就不正常了。
![image](https://user-images.githubusercontent.com/42933407/133356991-23093695-7e8a-4ffa-9b1a-3c5bdfab46e6.png)
markdown如下，编译后网站https://blog.gooday.press
```markdown
---
title: 测试
date: 2021-09-15 09:44:32
tags:
categories:
---
# 测试github action


```

**Comment by XPoet** [comment]
我刚刚测试了，发现突然有这个问题，我会尽快修复

**Comment by XPoet** [comment]
`v3.4.4` 已修复，请使用最新版本
