### ISSUE TITLE
友链不显示

### ISSUE THREAD

**Issue by 1258360186** [XPoet/hexo-theme-keep#117]
![image](https://user-images.githubusercontent.com/57449115/133882131-c5a1f05f-9839-46fb-9d81-d1e2621e2e84.png)
请问哪里出了问题呢？

**Comment by XPoet** [comment]
友链能正常显示，没改动，没问题。
请先在本地运行 hexo ，看看是否读取到了友链文件内容，如果能正常显示，请检查友链文件是否成功上传

**Comment by 1258360186** [comment]
本地也获取不到link.yml里的内容
![image](https://user-images.githubusercontent.com/57449115/133883386-cfc63e1a-a796-4b90-8436-c10f1c38d1fa.png)
控制台也没有报错

**Comment by XPoet** [comment]
提供下你使用的 Hexo 版本？

**Comment by 1258360186** [comment]
5.0.0

**Comment by XPoet** [comment]
Hexo 版本没问题。请提供下的 hexo 项目仓库地址，你这种情况就是没读取到 _data 里面的内容

**Comment by XPoet** [comment]
或者重新启动一下 hexo 项目

**Comment by 1258360186** [comment]
在官网用npm下的  
`npm install hexo-cli -g`

**Comment by 1258360186** [comment]
重启项目，问题仍存在

**Comment by 1258360186** [comment]
对links文件夹下markdown文件的修改可以显示

**Comment by XPoet** [comment]
提供你的 hexo 项目所有文件，我看看目录结构这些对不对

**Comment by 1258360186** [comment]
![image](https://user-images.githubusercontent.com/57449115/133884351-9d162ee8-add4-46f6-8227-869216faf197.png)

**Comment by XPoet** [comment]
把你 hexo 项目压缩打包发我一份
邮箱： i@xpoet.cn

**Comment by 1258360186** [comment]
请问是我的项目代码哪里没有注意导致的问题呢？

**Comment by XPoet** [comment]
我 hexo init 一个新项目，经过测试友链页面的显示是正常的。

![image](https://user-images.githubusercontent.com/24516169/134609051-28bcec02-e323-4561-8108-b80d98d864bf.png)

你的项目文件结构有点特别，keep 主题的配置文件都找不到，加我微信，细节私聊
