### ISSUE TITLE
自动换行的改进建议

### ISSUE THREAD

**Issue by XiaMoHuaHuo-CN** [XPoet/hexo-theme-keep#119]
现在这个自动换行还是有些问题，在page页面上，会超出边框，可看下图
![Screenshot_20211001-072558](https://user-images.githubusercontent.com/79651409/135543413-2da84570-e436-4fc5-a179-1874750b5f11.png)

**Comment by XPoet** [comment]
该场景无法复现，请提供下如图中的长链接。
或使用代码块来包裹长链接
```
https://github.com/xxxxxx/aaaaa/bbbbbbbb/ccccccccccc/111111?xx=99&bb=00000000000000000000
```

**Comment by XPoet** [comment]
无法复现，Issue 关闭
