### ISSUE TITLE
文章章节显示

### ISSUE THREAD

**Issue by 571941920** [XPoet/hexo-theme-keep#124]
![image](https://user-images.githubusercontent.com/52818048/139525508-9a606ecf-aac2-4161-9b09-777c72ee720e.png)
您好这个文章章节的前面的这个段落的符号从哪里去掉？

**Comment by 571941920** [comment]
![image](https://user-images.githubusercontent.com/52818048/139525818-4515bdc9-eed0-4309-84e1-6990d59b109a.png)
我直接从next主题切换过来，next没有问题，这里就会显示前面的段落符号

**Comment by XPoet** [comment]
这个符合我暂不清楚是哪儿冒出来
请使用 `hexo clean` 清空缓存，再使用 `hexo g` 重新生成试试

**Comment by 571941920** [comment]
谢谢了，我找到问题了，原因是markdown渲染器的问题，我安装了两个渲染器，卸载了hexo-renderer-marked，安装了hexo-renderer-marked-it。之后恢复正常了。
您做的主题真好看，希望早点加入更多的代码颜色主题！
