### ISSUE TITLE
文章版权信息模块配置-文章链接xians拼接错误

### ISSUE THREAD

**Issue by linzefan0612** [XPoet/hexo-theme-keep#126]
![image](https://user-images.githubusercontent.com/52768739/140631656-72771cef-17c2-4143-be78-42140aa02f31.png)

博客在子目录里边0 0，文章链接的拼接显示有问题喔

**Comment by XPoet** [comment]
收到反馈。尽快修复

**Comment by XPoet** [comment]
@linzefan0612 
麻烦提供下你的文章目录结构（未编译前的 md ），便于排查问题

**Comment by linzefan0612** [comment]
![Uploading Snipaste_2021-11-17_22-15-06.png…]()

**Comment by linzefan0612** [comment]
![image](https://user-images.githubusercontent.com/52768739/142217755-fb2433c0-de09-4a70-8996-411af3e41164.png)

**Comment by XPoet** [comment]
`v3.4.4` 已修复，请使用最新版本
