### ISSUE TITLE
在Keep主题中关闭指定文章的Table of Contents(TOC)

### ISSUE THREAD

**Issue by SilhouettesForYou** [XPoet/hexo-theme-keep#128]
参考了[<<在Hexo NexT主题中关闭指定文章的Table of Contents(TOC)>>](https://blog.csdn.net/qq_44766883/article/details/113478757)这篇博客修改了`toc.ejs`，并测试成功！
在front-matter加上`toc: true | false`
```
title: Latex公式
date: 2021-11-22 19:13:53
categories:
- Latex
tags:
- 符号
- 公式
mathjax: true
toc: true
```
* [打开目录例子](https://silhouettesforyou.github.io/2021/11/22/19/)
* [关闭目录例子](https://silhouettesforyou.github.io/2021/11/15/14/)

> `toc.ejs`
> ```
> <% if (page.toc) { %>
>    <div class="post-toc-wrap">
>        <div class="post-toc">
>            <%- toc(
>                    page.content,
>                    {
>                        class: 'nav',
>                        list_number: theme.toc.number
>                    }
>            ) %>
>        </div>
>    </div>
> <% } %>
> ```

**Comment by XPoet** [comment]
可以提个 PR 进来。
记得往 **dev** 分支提

**Comment by XPoet** [comment]
Keep 主题 v3.4.6 已支持该功能，请使用最新版本。

```
npm install hexo-theme-keep@3.4.6
```
