### ISSUE TITLE
移动端访问代码有时会变很大

### ISSUE THREAD

**Issue by miyu233** [XPoet/hexo-theme-keep#129]
![IMG_2650](https://user-images.githubusercontent.com/59055460/143798297-44f4ba3f-6fda-494e-bd1b-2dba5e8dae9b.PNG)
![IMG_2651](https://user-images.githubusercontent.com/59055460/143798312-4f97b106-f7d2-4a1c-b350-ca9558df7378.PNG)

部分代码显示正常，但是大部分都是如下图所示

**Comment by XPoet** [comment]
@miyu233 
请提供下你使用的手机系统及浏览器，我在移动端测试发现一切正常

**Comment by miyu233** [comment]
手机型号iphonexr，系统ios14.4，Safari浏览器。我朋友鸿蒙系统自带浏览器浏览也一切正常。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月4日(星期六) 下午4:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [XPoet/hexo-theme-keep] 移动端访问代码有时会变很大 (Issue #129)





 
@miyu233
 请提供下你使用的手机系统及浏览器，我在移动端测试发现一切正常
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by XPoet** [comment]
我没有 iPhone XR 手机，可能不好调试。
你看看你手机上的其他浏览器上会不会这样

**Comment by miyu233** [comment]
好的，我试试



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 指间的诗意 ***@***.***&gt;
发送时间: 2021年12月4日 17:25
收件人: XPoet/hexo-theme-keep ***@***.***&gt;
抄送: ZOU ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[XPoet/hexo-theme-keep] 移动端访问代码有时会变很大 (Issue #129)

**Comment by Xuu6770** [comment]
- 设备：iPhone 11
 - 系统版本：iOS 15.1
 - 浏览器：Safari 
 - 主题版本：3.4.5

同样的问题。

**Comment by XPoet** [comment]
@Xuu6770 
作者用的不是苹果手机，后续会优化该问题

**Comment by xiwuqi** [comment]
> @Xuu6770 作者用的不是苹果手机，后续会优化该问题

问题已缩小范围

- 设备：iphone
- 系统：IOS
- 浏览器：一切国外的浏览器（如：Google、Safari、Firefox...）
- 主题版本：3.4.5
- 问题代码框：一切不已`/`（反斜杠）开头的代码框（具体情况如下图所示）

![2022_7_14_0](https://cdn.staticaly.com/gh/xiwuqi/image-hosting@master/blog_posts/2022_7_14_0.27e89cmrvtog.webp)
注：经测试一切国产浏览器都正常显示（百度、UC、夸克...）

**Comment by xiwuqi** [comment]
> @Xuu6770 作者用的不是苹果手机，后续会优化该问题

问题已缩小范围

设备：iphone
系统：IOS
浏览器：一切国外的浏览器（如：Google、Safari、Firefox...）
主题版本：3.4.5
问题代码框：一切不已/（反斜杠）开头的代码框（具体情况如下图所示）
![2022_08_01_0](https://cdn.staticaly.com/gh/xiwuqi/image-hosting@master/blog_posts/2022_08_01_0.1kl8im4ppa8w.webp)
注：经测试一切国产浏览器都正常显示（百度、UC、夸克...）

**Comment by xiwuqi** [comment]
> @Xuu6770 作者用的不是苹果手机，后续会优化该问题

问题已缩小范围

- 设备：iPhone
- 系统版本：iOS
- 浏览器：一切国外浏览器（如：Google、Safari、Firefox...)
- 主题版本：3.4.5
- 问题代码框：一切非`/`（斜杠）开头的代码框（主要情况如下图所示）
![2022_08_01_0]<img src="https://cdn.staticaly.com/gh/xiwuqi/image-hosting@master/blog_posts/2022_08_01_0.1kl8im4ppa8w.webp" alt="2022_08_01_0" style="zoom: 20%;" />
注：经测试国产浏览器上一切正常（百度、UC、夸克...）

**Comment by XPoet** [comment]
@xiwuqi 
感谢提供这么详细的测试报告，作者会重点优化

**Comment by kechocy** [comment]
> @xiwuqi
> 感谢提供这么详细的测试报告，作者会重点优化

我为`themes/keep/source/css/common/codeblock/highlight.styl` 中的 `code-block` 设置` -webkit-text-size-adjust: none; `就好了

**Comment by xiwuqi** [comment]
> > @xiwuqi
> > 感谢提供这么详细的测试报告，作者会重点优化
> 
> 我为`themes/keep/source/css/common/codeblock/highlight.styl` 中的 `code-block` 设置`-webkit-text-size-adjust: none;`就好了

非常感谢，问题已经解决

**Comment by XPoet** [comment]
@kechocy 感谢提供解决方法

**Comment by XPoet** [comment]
@kechocy 感谢提供解决方法

**Comment by XPoet** [comment]
这个问题已在 `v3.4.9` 优化，请大家使用最新版本。

```
npm i hexo-theme-keep@latest
```
