### ISSUE TITLE
图片居中

### ISSUE THREAD

**Issue by yyyac** [XPoet/hexo-theme-keep#133]
请问如何让博客图片默认居中

**Comment by XPoet** [comment]
https://keep-docs.xpoet.cn/usage-tutorial/configuration-guide.html#avatar

![image](https://user-images.githubusercontent.com/24516169/148732381-54586fad-9abf-42c2-8e06-8b0ed3562665.png)


在 keep 主题配置文件，设置：
```yml
article_img_align: center
```

**Comment by yyyac** [comment]
感谢，已解决
