### ISSUE TITLE
作者你好，问一个关于keep主题的twikoo配置问题

### ISSUE THREAD

**Issue by imzql** [XPoet/hexo-theme-keep#134]
我是将Twikoo 部署到 Vercel，填好了环境id 但是评论无法显示 该如何解决呢
[![77OfwF.md.png](https://s4.ax1x.com/2022/01/25/77OfwF.md.png)](https://imgtu.com/i/77OfwF)

**Comment by XPoet** [comment]
不清楚，这类问题请询问  twikoo 评论插件作者。
只要正确配置，twikoo 是可以显示的。
