### ISSUE TITLE
功能建议 是否可增加一个喜欢文章的按钮 以及 文章分享按钮

### ISSUE THREAD

**Issue by iZhengXi** [XPoet/hexo-theme-keep#137]
功能建议 是否可增加一个喜欢文章的按钮 以及 文章分享按钮

**Comment by XPoet** [comment]
有这个打算，后续版本会加上

**Comment by XPoet** [comment]
该需求需要后端数据库存储能力支持，暂时不做迭代，等后期作者写一个 hexo 插件后再集成进来

**Comment by XPoet** [comment]
<img width="747" alt="image" src="https://github.com/XPoet/hexo-theme-keep/assets/24516169/9556526c-a3ea-4c54-9afd-fd8c33c5e645">

Keep 主题已支持文章分享功能，在文章页面的末尾可以找到相应的分享按钮
