### ISSUE TITLE
优化建议：手机空间有限，建议去掉两边的 padding 以及阴影，保留正文 padding

### ISSUE THREAD

**Issue by yx208** [XPoet/hexo-theme-keep#140]
![image](https://user-images.githubusercontent.com/48788026/156981000-65a5cd8d-36fe-49a7-8fcc-644d9db03086.png)

**Comment by XPoet** [comment]
挺好的建议，后续版本升级会做优化

**Comment by XPoet** [comment]
Keep 主题 v3.4.6 已支持该功能，请使用最新版本。

```
npm install hexo-theme-keep@3.4.6
```
