### ISSUE TITLE
两个建议，更换为字节cdn？

### ISSUE THREAD

**Issue by CS123n** [XPoet/hexo-theme-keep#144]
2. 表格无法显示边框，看起来很乱，希望能加上。
![image](https://user-images.githubusercontent.com/102355527/161378136-b21c88cd-1438-47e7-b3ae-97b03ff440f6.png)
4. jsdelivr的cdn现在速度并不快。能否换为类似这个http://cdn.bytedance.com/?query=hexo-theme-next&version=8.10.0

**Comment by CS123n** [comment]
自顶

**Comment by XPoet** [comment]
1、表格是有边框的
<img width="915" alt="image" src="https://user-images.githubusercontent.com/24516169/192299529-3cfa0692-0375-4622-8690-c2cb997c661c.png">

<img width="906" alt="image" src="https://user-images.githubusercontent.com/24516169/192299605-20e7b197-6389-4fc6-a0bd-e4831cbdd842.png">

是否你的 md 写法有误？

2、后续会增加其他 cdn 选项，可自由切换

**Comment by XPoet** [comment]
https://xpoet.cn/2017/10/%E5%BF%AB%E9%80%9F%E6%8E%8C%E6%8F%A1Markdown%E5%9F%BA%E7%A1%80%E8%AF%AD%E6%B3%95/

参考这篇文章
