### ISSUE TITLE
关于使用的一些bug请教

### ISSUE THREAD

**Issue by songbiaoself** [XPoet/hexo-theme-keep#147]
出现了几处报错，页面变成css乱码，我在正常的一次提交文章后就变成这样了。很郁闷
![image](https://user-images.githubusercontent.com/52911891/162254687-4e1e5052-c28c-4263-839d-70793e1a2e67.png)
还请执教！

**Comment by EvanNotFound** [comment]
重新部署

**Comment by XPoet** [comment]
这个问题非常不好定位，最好的建议是重新 hexo clean -> hexo d
