### ISSUE TITLE
关于图标的问题

### ISSUE THREAD

**Issue by cupscc** [XPoet/hexo-theme-keep#149]
我使用的是gitpages
我在配置keep主题的过程中设置了新的avatar和新的favicon
但是在hexo d之后并没有得到相应的效果，我使用元素检查发现相应位置的html代码为
![image](https://user-images.githubusercontent.com/73223782/162617133-04fe9c5e-aa5b-45b6-890c-178b956c13a6.png)
我在我的gitpage仓库中将路径修改成正确的之后出现我想要的效果。
然而我每次运行完hexo -d 这个路径都会被重写成上面图片中的效果。
这是一个Bug 还是我需要配置其他内容？

**Comment by XPoet** [comment]
keep 主题没有这个 bug，avatar 和 favicon 都可以正常配置使用

**Comment by XPoet** [comment]
你提供一下 keep 主题配置文件，我这边帮你看看配置项是否有写对

**Comment by XPoet** [comment]
你把图片都换成图片链接形式即可。
可以使用 PicX 来生成图片链接
https://github.com/XPoet/picx
