### ISSUE TITLE
关于友链页面

### ISSUE THREAD

**Issue by Paraderno** [XPoet/hexo-theme-keep#150]
本地服务器显示正常
![image](https://raw.githubusercontent.com/Paraderno/image-hosting/master/image.4ghhn8ry4600.png)

上传到 github 之后显示有 bug

![image](https://raw.githubusercontent.com/Paraderno/image-hosting/master/image.7gs2ntq29ms0.png)

[博客链接](https://paraderno.github.io/Blog.github.io/)

**Comment by Aewait** [comment]
尝试使用`ctrl+f5`进行强制刷新，或者尝试换一个浏览器（没错我edge有bug。火狐没有）
