### ISSUE TITLE
关于目录树TOC的位置建议

### ISSUE THREAD

**Issue by kechocy** [XPoet/hexo-theme-keep#152]
希望电脑端网页中左侧目录树的位置能往下移，目前看起来不太协调，而且它的开启或关闭会影响顶部导航栏中字体位置发生改变，尤其是顶部字体较多时开启目录树会导致字都挤一块
![9E3B747E-FC19-4ACD-9500-D6E951CAB01E](https://user-images.githubusercontent.com/61276192/163683854-b2762b51-d736-4c13-918d-02f9d02542f0.jpeg)
![E839222C-28BA-4A60-91D8-91F678F1F71E](https://user-images.githubusercontent.com/61276192/163683859-d9ff9445-9bb6-4fa2-b92d-09f6caf035b4.jpeg)

**Comment by Paraderno** [comment]
突然看到我博客的截图，有点惊讶www

**Comment by seed-words** [comment]
> 突然看到我博客的截图，有点惊讶www

博客很好看，请问 hover 链接变色和 card 那个效果怎么实现的？

**Comment by XPoet** [comment]
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/24516169/199195594-41d17674-ae09-4ff1-aea4-c1d874c11062.png">

Keep 主题 TOC 目录结构已更新，请大家使用最新版本

**Comment by XPoet** [comment]
> > 突然看到我博客的截图，有点惊讶www
> 
> 博客很好看，请问 hover 链接变色和 card 那个效果怎么实现的？

这些都是 Keep 主题自带的功能，官方使用文档上面都有教程怎么设置
