### ISSUE TITLE
fontawesome版本更新

### ISSUE THREAD

**Issue by hjgsy110** [XPoet/hexo-theme-keep#155]
现在keep支持的是5.15.4那个版本，fontawesome最新的6.1.1多了很多图标，希望能进行更新支持

**Comment by EvanNotFound** [comment]
可以自己替换 webfonts 文件夹和 `fontawesome.min.js`，并且在主题 `head` 里面增加 fontawesome 其他模块图标的链接。

参考我的博客：https://www.evanluo.top

**Comment by XPoet** [comment]
Keep 主题 v3.4.6 已支持该功能，请使用最新版本 `npm i hexo-theme-keep`

Fontawesome 图标库 v6.2.0
