### ISSUE TITLE
【紧急求助】请求作者大大换个 CDN

### ISSUE THREAD

**Issue by Kukmoon** [XPoet/hexo-theme-keep#158]
Keep 主题部分资源使用了 jsDelivr 的 CDN，但是如今 jsDelivr 在墙内已经彻底无法访问，影响了使用 Keep 主题的用户（其中有一位是我客户），因此我请求作者大大能否出一版更新，用 baomitu.com 之类的墙内 CDN 代替 jsDelivr？

**Comment by XPoet** [comment]
@Kukmoon 
你可以先关闭 cdn 功能。
```
cdn:
  enable: false
```
jsDelivr 并非不能用了，现在比较慢，作者正在寻求新的解决方案

**Comment by Kukmoon** [comment]
您好，大大，我已经把它关了…不过npm也有够慢，不如国内快…

发自我的iPad

**Comment by cemonliu** [comment]
JsDelivr的确很不稳定，我的github图床引用链接都是用jsDelivr的，有没有办法批量替换

**Comment by Aewait** [comment]
> 

gitee图床在3月份开始有了防盗链，现在基本是不太可用的状态。国内可以尝试使用阿里云OSS，价格不贵。在访问量不高的情况下，一个月只要1-3元

**Comment by HayatoOvO** [comment]
> @Kukmoon 你可以先关闭 cdn 功能。
> 
> ```
> cdn:
>   enable: false
> ```
> 
> jsDelivr 并非不能用了，现在比较慢，作者正在寻求新的解决方案

我记得 Unpkg 目前的访问效果是比较可观的。

**Comment by XPoet** [comment]
Keep 主题 v3.4.6 已支持该功能，请使用最新版本 `npm i hexo-theme-keep`

```
cdn:
  enable: false       # Option values: true | false
  provider: jsdelivr  # Option values: jsdelivr | unpkg
```
