### ISSUE TITLE
Feature Image

### ISSUE THREAD

**Issue by mrfoxie** [XPoet/hexo-theme-keep#160]
I switched my blog from the [old blog](https://www.mistrysiddh.tk) to a [new blog](https://mistrysiddh.com) so I was trying to figure out how to add a featured image to my blog post.

Old Blog View:
![Old Blog View](https://user-images.githubusercontent.com/25217451/174634768-c0cb2721-e49e-4635-a1b8-bd7c2d021e24.png)

New Blog View:
![New Blog View](https://user-images.githubusercontent.com/25217451/174633438-b4e5daa7-d34d-4280-b93b-7a1422f82e85.png)

**Comment by EvanNotFound** [comment]
Keep theme does not have this fuction. You can edit theme files to add feature imgs.

**Comment by XPoet** [comment]
> 

yes

**Comment by XPoet** [comment]
> Keep theme does not have this fuction. You can edit theme files to add feature imgs.

yes
