### ISSUE TITLE
功能适配：Twikoo部署在Vercel上

### ISSUE THREAD

**Issue by NoctuG** [XPoet/hexo-theme-keep#163]
https://twikoo.js.org/quick-start.html#vercel-%E9%83%A8%E7%BD%B2

Twikoo 现已支持 Vercel 部署，但主题中 `envID` 尚不支持 Vercel 地址，烦请作者进行一下适配，谢谢。

PS：这一情况下 `region` 可以不填

**Comment by localhosts-A** [comment]
感觉作者不会理

**Comment by EvanNotFound** [comment]
### 解决办法
只要打开主题文件夹下的 `layout/_partial/comment/twikoo.ejs` 文件，然后把 `//cdn.jsdelivr.net/npm/twikoo@1.0.0/dist/twikoo.all.min.js` 替换为 `https://cdn.staticfile.org/twikoo/1.6.7/twikoo.all.min.js` 就行了。
之后如果要用 vercel 就可以只填 `envID`，`region` 留空就行

 @XPoet 
已经提交了pr，请看一下
