### ISSUE TITLE
博客大纲浏览的一个小bug

### ISSUE THREAD

**Issue by LuLu010722** [XPoet/hexo-theme-keep#170]
阅读一个博客的时候，可以点开右上角的**展开/收起**大纲按钮
点击了里面的一个标题之后，顶部导航栏消失了，收起大纲，点击任何地方，导航栏都不会再次出现
不方便导航回到其他页面
![image](https://user-images.githubusercontent.com/62323571/190553308-48ac2ffa-7f68-4f22-bde7-1de50771e554.png)
![image](https://user-images.githubusercontent.com/62323571/190553347-de70c717-cdbe-4a7a-a718-134335c2a94a.png)

**Comment by EvanNotFound** [comment]
无法复现bug，你可以去我博客看看，我的是正常的

https://www.evanluo.top/demos.html

你的可能是因为文章太短了，只有一个标题

**Comment by LuLu010722** [comment]
哈哈有可能，算是个小bug吧
