### ISSUE TITLE
代码块添加语言种类

### ISSUE THREAD

**Issue by zhaozkTHU** [XPoet/hexo-theme-keep#171]
能否在代码块显示语言种类呢？比如区别c/c++,js/ts
就像这样子
<img width="547" alt="image" src="https://user-images.githubusercontent.com/92924106/191444291-ed3e219b-fba0-4bcb-a3df-a8ceab012b0c.png">

**Comment by XPoet** [comment]
好建议，后续版本会加上

**Comment by XPoet** [comment]
keep `v3.4.8` 已支持该功能，请使用最新版本。

<img width="883" alt="image" src="https://user-images.githubusercontent.com/24516169/193205372-b1912b6d-1f5c-4821-a23c-aafbd05e518f.png">
