### ISSUE TITLE
希望能在博客首頁的文章列表中，設定顯示每一篇文章內的圖片

### ISSUE THREAD

**Issue by taiwan-dentist** [XPoet/hexo-theme-keep#179]
希望能在博客首頁的文章列表中，自行設定是否要"顯示每一篇文章裡的第一張圖片縮圖"
如圖~
研究很久不知這個功能的代碼怎麼寫
希望大佬更新了，感謝
![螢幕擷取畫面 2022-10-21 142950](https://user-images.githubusercontent.com/77205775/197128444-d7753b05-4be9-44a9-8fb1-c1740cfa26ab.jpg)

**Comment by XPoet** [comment]
该需求已实现，请使用 Keep 主题最新版本 `v3.7.1`。

参考文档：
http://localhost:5173/advanced/front-matter.html#%E9%85%8D%E7%BD%AE%E6%96%87%E7%AB%A0%E5%B0%81%E9%9D%A2
