### ISSUE TITLE
文档链接 404 了

### ISSUE THREAD

**Issue by BainDragneel** [XPoet/hexo-theme-keep#180]
文档链接 404 了

**Comment by XPoet** [comment]
官方文档近期维护，暂时下线，先看这份教程

https://juejin.cn/post/6943622313447260190

**Comment by BainDragneel** [comment]
好的 谢谢！

**Comment by XPoet** [comment]
https://keep-docs.xpoet.cn/

Keep 主题官方文档已恢复
