### ISSUE TITLE
首页按照文章更新时间排序问题

### ISSUE THREAD

**Issue by w749** [XPoet/hexo-theme-keep#190]
今天刚开始使用keep主题，之前使用的主题没有显示文章更新时间的地方，就是按照markdown中的date排序
不太清楚这个文章更新时间是从哪里生成的，我所有的文章更新时间都是一样的，我不记得我在这个时间点做过什么操作，是否有配置项选择使用文章创建时间来排序文章

![image](https://user-images.githubusercontent.com/39213602/210051745-27652755-3afa-4144-a803-4d05133ce3d7.png)

![image](https://user-images.githubusercontent.com/39213602/210051847-384d523a-8719-48a7-8694-5c57d7ef989b.png)

![image](https://user-images.githubusercontent.com/39213602/210051710-276c82c3-4f8f-42e3-991b-6469725c1ebe.png)

**Comment by XPoet** [comment]
<img width="484" alt="image" src="https://user-images.githubusercontent.com/24516169/210319017-aa29de95-7bf0-43e3-a907-3c58921a3902.png">

在首页是根据文章创建时间来排序的。

**Comment by XPoet** [comment]
<img width="156" alt="image" src="https://user-images.githubusercontent.com/24516169/210319199-05db7e9c-7032-4f9b-91f3-83318b241b26.png">
你这里显示一致，很可能是因为你使用了自动部署，使用自动部署会导致所有文章的更新时间被重写，具体的解决方法，你在网上搜一下，有对应方案

**Comment by XPoet** [comment]
可以分享一下你的解决方法，以便帮助到其他小伙伴

**Comment by w749** [comment]
没问题，出现这个问题的原因是因为使用自动部署并且文章中没有updated标签而产生的，这是我之前的文章内容
```markdown
---
title: ELK命令语法详解
author: 汪寻
date: 2020-10-18
tags:
 - ES
categories:
 - Software
---
```

然后我写了个shell脚本放在博客根目录下，执行后为每个文章添加了updated标签，updated日期部分和date一样，时间部分是随机生成的，比date对应的时间晚了1-30分钟，这是修改后的文章内容
```markdown
---
title: ELK命令语法详解
author: 汪寻
date: 2020-10-18 10:17:12
updated: 2020-10-18 10:32:46
tags:
 - ES
categories:
 - Software
---
```
这是我的shell脚本 [add-update-time.sh](https://github.com/w749/blog/blob/main/add-update-time.sh)，不需要参数直接执行就可以，注意脚本位置

解决思路参考 [hexo自动更新文章修改时间](https://www.cnblogs.com/yyyzyyyz/p/15792199.html)，他是用js写的，并且通过修改`scaffolds/post.md`使得执行`hexo new post`命令时自动添加updated字段

这是修改后的效果
![image](https://user-images.githubusercontent.com/39213602/211697555-d33e6292-ef91-4dd2-8b96-c63dc185eaa8.png)
