### ISSUE TITLE
运行hexo，themes\keep\scripts\helpers\helper.js文件报语法错误

### ISSUE THREAD

**Issue by p0mel0** [XPoet/hexo-theme-keep#191]
![image](https://user-images.githubusercontent.com/37646522/210215404-317390e3-ce51-4915-969c-7fae4fd0b5ed.png)

**Comment by XPoet** [comment]
1、请将你的 Node.js 升级至 v14 以上
2、Hexo 已经出 v6 了，建议使用新版

**Comment by p0mel0** [comment]
好的，居然木有兼容，我觉得可以再README中说明下适配的版本哈

**Comment by XPoet** [comment]
<img width="169" alt="image" src="https://user-images.githubusercontent.com/24516169/210328494-18d80173-b7b3-43d0-a230-d1417aea1000.png">

<img width="792" alt="image" src="https://user-images.githubusercontent.com/24516169/210328648-d7885b71-1042-4dee-8dc6-7f55db1aa837.png">

Node.js v14 已是 N 多年前的了

不是没写，是你没看到而已

**Comment by p0mel0** [comment]
OK
