### ISSUE TITLE
侧边目录关闭展开按钮位置异常

### ISSUE THREAD

**Issue by lzlcs** [XPoet/hexo-theme-keep#192]
多次点击此按钮之后, 会出现位置异常现象
![image](https://user-images.githubusercontent.com/61308957/210543671-fa5a4401-5c5c-4670-9614-9f5a37fd4062.png)

**Comment by Proteinlzl** [comment]
(吐槽: 闲得蛋疼才会发现这个bug)

**Comment by Proteinlzl** [comment]
补充: 概率性事件

**Comment by Proteinlzl** [comment]
补充: 概率性事件

**Comment by XPoet** [comment]
😅 难于复现，后续将会完善
