### ISSUE TITLE
希望能添加Artalk评论系统

### ISSUE THREAD

**Issue by musnows** [XPoet/hexo-theme-keep#193]
https://artalk.js.org/

https://github.com/ArtalkJS/Artalk

个人感觉这个系统很好用，配置比valine的leancloud方便多了（特别是邮箱提醒）

缺点嘛，那就是需要一个服务器跑后端

**Comment by XPoet** [comment]
挺不错，后续版本将支持

**Comment by musnows** [comment]
感谢！
