### ISSUE TITLE
希望可以添加指定文章copyright_info的关闭功能

### ISSUE THREAD

**Issue by Aewait** [XPoet/hexo-theme-keep#196]
如题，部分文章是从别站**转载**的，在附上了**文章转载信息**的情况下，希望可以在md文件的首部添加 `copyright_info: false`选项（大概就是和关闭评论，关闭toc目录一样的设置），在本页取消本站创作信息的展示；

![image](https://user-images.githubusercontent.com/87506951/211526050-539eb771-2a25-425e-a42e-ec7ebb45ef2a.png)

```
---
title: Keep 主题使用指南
date: 2020-04-07 21:55:14
tags: [Hexo]
categories: [Hexo]
sticky: 999
copyright_info: false
---
```
麻烦作者大哥了

**Comment by XPoet** [comment]
该功能已实现，请使用最新版本的 Keep 主题。

```
---
title: Keep 主题使用指南
date: 2020-04-07 21:55:14
tags: [Hexo, Keep]
categories: [Keep]
sticky: 9999
copyright_info: false
---
```

**Comment by Aewait** [comment]
更新测试了一下，可以用了！👌
