### ISSUE TITLE
调整在主页预览的博客内图片大小

### ISSUE THREAD

**Issue by MrAgNO3** [XPoet/hexo-theme-keep#199]
博客的预览内容中有图片时，图片会按原大小显示。
如果图片尺寸较大的话，就会占据空间且不美观

建议统一在主页预览的图片的高度/尺寸

**Comment by XPoet** [comment]
收到反馈，截个图我看下

**Comment by MrAgNO3** [comment]
> 收到反馈，截个图我看下
如图

![localhost_8001_](https://user-images.githubusercontent.com/74173773/212471185-94fa8a0a-b918-4ea8-a44d-296cc5d06742.png)

**Comment by XPoet** [comment]
这是非常极端的情况，不应该从全局来处理。
你可以单独对这张图片做宽高限制的处理，例如：
```
<img style="height: 10%;" src="https://cdn.staticaly.com/gh/XPoet/image-hosting@master/FE-Cheerleaders/FEC-Card.76dbi8n1bkk0.png">
```
