### ISSUE TITLE
[功能建议]: 加入自定义引入css或js的选项

### ISSUE THREAD

**Issue by HanBiWolf** [XPoet/hexo-theme-keep#205]
www.hanbiwolf.cc
我自己为了方便更新用的是npm安装主题
但是发现主题里没有引入自定义css或者js的选项
加东西只能改源代码
但是感觉npm那边一更新我又得重新改了,所以感觉在主题配置里加上一个选项会比较好:)

**Comment by musnows** [comment]
建议用git的方式安装，这样下次pull的时候能通过git改冲突。npm直接覆盖了，有些麻烦

我现在就是用git操作的

**Comment by XPoet** [comment]
后续版本会加上这个功能

**Comment by XPoet** [comment]
该功能已实现，请使用 Keep 主题最新版本 v3.7.1。

参考文档：
http://localhost:5173/tutorial/configuration-guide/inject.html
