### ISSUE TITLE
[功能建议]：希望能隐藏文章顶上修改日期

### ISSUE THREAD

**Issue by imxhe** [XPoet/hexo-theme-keep#206]
如图，希望前面的创建时间的时分秒也可以自定义格式或者隐藏
![1](https://s1.vika.cn/space/2023/02/22/83c36b1e687b4d409077ab301e5764b2)

**Comment by 603681955** [comment]
+1

**Comment by 1blog** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by XPoet** [comment]
下个版本增加可关闭的配置项

**Comment by XPoet** [comment]
该功能已实现，请使用 Keep 主题 v3.7.1 及以上版本。

配置教程详情参考文档：

https://keep-docs.xpoet.cn/tutorial/configuration-guide/post.html#datetime
