### ISSUE TITLE
功能建议：希望友链界面可以自适应移动端

### ISSUE THREAD

**Issue by imxhe** [XPoet/hexo-theme-keep#207]
pc端看着挺不错的，但是移动端两列就显得有些拥挤，有些博客名字和介绍都不能显示完全，如果移动端可以自适应改成1列就完美了
![](https://s1.vika.cn/space/2023/02/23/cce760d5503e41f7af82e4cde5f306f6)

**Comment by XPoet** [comment]
该需求已实现，请使用 Keep 主题 v3.7.1 及以上版本。

<img width="294" alt="image" src="https://github.com/XPoet/hexo-theme-keep/assets/24516169/8bc0cb6c-3ae7-4883-82e3-abebf40cc075">
