### ISSUE TITLE
同级分类显示不合适

### ISSUE THREAD

**Issue by bianyukun1213** [XPoet/hexo-theme-keep#209]
假如说一篇文章有如下的同级分类：

``` yml
categories:
  - [影视]
  - [游戏]
```

在文章页面仍然按照“游戏是影视的子分类”的逻辑显示成 `影视 > 游戏`，但实际需要的效果是 `影视 | 游戏`。希望能优化此处的设计。

**Comment by XPoet** [comment]
在 Hexo 框架中，分类没有同级的说法，也就是说有且仅有一个一级分类。
想要同级就设置 Tag。

![image](https://github.com/XPoet/hexo-theme-keep/assets/24516169/6ecb39d5-a130-49f8-9e0f-fa4a6d461ee2)

![image](https://github.com/XPoet/hexo-theme-keep/assets/24516169/b199cf8f-9f0e-4a94-b965-2b68d0b89f65)
