### ISSUE TITLE
百度收录失败

### ISSUE THREAD

**Issue by ssk-wh** [XPoet/hexo-theme-keep#211]
我按照百度的说明丢了一个baidu*.html放到根目录下的source文件夹，通过hexo g后，发现这个文件虽然是处在public目录下了，但里面的内容和index.html是一样的，我希望的是不要修改这个文件的内容，我不确定这是hexo还是keep的问题，我目前只用过keep

**Comment by XPoet** [comment]
跟主题无关，你去搜一下，有 hexo 插件，可以帮你完成收录

**Comment by ssk-wh** [comment]
好的，谢谢，我用插件去尝试下
