### ISSUE TITLE
功能建议：支持自定义图标

### ISSUE THREAD

**Issue by Hakuin123** [XPoet/hexo-theme-keep#213]
目前social_contact采用的是“Font Awesome v6.2.0 免费版图标”，但实际体验发现仍有所想要的图标缺失问题

另外也有较为小众的图标需求，需要自定义图标实现

请求支持自定义图标

**Comment by XPoet** [comment]
Keep v3.8.6 已支持在 `social_contact ` 上使用任意自定义的图标，具体教程查看 [官方文档](https://keep-docs.xpoet.cn/basis/configuration-guide/social_contact.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%BD%BF%E7%94%A8%E4%BB%BB%E6%84%8F-svg-%E5%9B%BE%E6%A0%87)

**Comment by Hakuin123** [comment]
Thanks!
