### ISSUE TITLE
部署码云后，First screen background image加载不出来

### ISSUE THREAD

**Issue by gaohuiluo** [XPoet/hexo-theme-keep#214]
本地可以加载出来，但是**部署到码云后主页图加载不出来**。外链图片在文章中引用可以在部署码云后可以查看

   
 # First screen background image (You can use local image or image external link)
    background_img: https://cdn.staticaly.com/gh/gaohuiluo/picx-images-hosting@master/landscape-gd4f7338b5_1920 (1).56aee9i248o0.webp

**Comment by XPoet** [comment]
作者也不清楚具体原因，建议你不要使用 Gitee，转向 GitHub Pages 或 Vercel，你会发现少了好多烦恼
