### ISSUE TITLE
latex渲染

### ISSUE THREAD

**Issue by NiceAsiv** [XPoet/hexo-theme-keep#215]
希望能增加对katex的支持，mathjax支持的公式有部分渲染不出来，非常感谢

**Comment by LeeHero0803** [comment]
附议，像矩阵之类的多行公式完全无法显示

**Comment by AnpyDX** [comment]
用 pandoc 替代原来的渲染器试试，换行的问题好像解决了

用下面的命令替换原来的渲染器（需要提前安装pandoc）
```bash
npm uninstall hexo-renderer-marked
npm install hexo-renderer-pandoc
```

**Comment by XPoet** [comment]
LaTex 渲染不出来，不属于 Keep 主题本身的问题，更换其他的渲染器即可。
例如更换 [hexo-renderer-markdown-it-plus](https://github.com/CHENXCHEN/hexo-renderer-markdown-it-plus)

在你的 Hexo 项目根目录：

```sh
# 卸载 Hexo 默认的 Markdown 渲染器
npm uninstall hexo-renderer-marked

# 安装新的 Markdown 渲染器
npm install hexo-renderer-markdown-it-plus
```
