### ISSUE TITLE
关于返回顶部按钮

### ISSUE THREAD

**Issue by LUKECLEVER** [XPoet/hexo-theme-keep#216]
在点击返回顶部按钮时出现卡顿，而且在返回顶部后如果继续向下滚动页面又会出现返回顶部的操作，需要手动向上滚动页面才可以正常向下翻页

用户代理字符串：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.68

出现问题网址：https://gnest.luyaoguagua.top/
按钮位于网页右侧下方。

**Comment by XPoet** [comment]
无法复现
