### ISSUE TITLE
[功能建议]  最好是代码块能够具有直接复制的功能

### ISSUE THREAD

**Issue by Drun1baby** [XPoet/hexo-theme-keep#218]

**Comment by XPoet** [comment]
Keep 主题目前是具备代码块复制功能
<img width="928" alt="image" src="https://github.com/XPoet/hexo-theme-keep/assets/24516169/4e77bbe6-3329-42a3-a6f4-a96e73a7b3d6">

**Comment by XPoet** [comment]
<img width="780" alt="image" src="https://github.com/XPoet/hexo-theme-keep/assets/24516169/665fbfce-a2e6-45cd-bcf6-03654c0c9791">

**Comment by Drun1baby** [comment]
> <img alt="image" width="780" src="https://user-images.githubusercontent.com/24516169/241611632-665fbfce-a2e6-45cd-bcf6-03654c0c9791.png">

我这里是照做了，但是并没有出现复制这一选项

**Comment by Drun1baby** [comment]
![image](https://github.com/XPoet/hexo-theme-keep/assets/75228348/11ad3954-379b-4e3c-92d7-af4ac6ea6039)

![image](https://github.com/XPoet/hexo-theme-keep/assets/75228348/b118191d-5434-4318-8dd1-c2b70d7140e0)

**Comment by XPoet** [comment]
首先 Keep 主题是具备代码块复制功能的，该功能稳定可靠。
作者无法推测你的 Hexo 项目代码场景，强烈建议你下载 Keep 主题快速启动模块，基于该模板来搭建你的博客
https://github.com/theme-keep/hexo-theme-keep-starter
