### ISSUE TITLE
期望能够优化一下分页和toc

### ISSUE THREAD

**Issue by bluestar1993** [XPoet/hexo-theme-keep#219]
期望能优化一下主页的分页功能，能够显示当前页和总页数，能够跳转页数。
期望能够配置文章页面中toc的布局，可以居左或居右。
移动端也可显示toc

**Comment by XPoet** [comment]
该需求已实现，请使用 Keep 主题 v3.7.1 及以上版本。

配置教程详情参考文档：
https://keep-docs.xpoet.cn/tutorial/configuration-guide/toc.html#layout
