### ISSUE TITLE
我创建的分类页和标签页的内容是空白的咋回事？

### ISSUE THREAD

**Issue by mxdldev** [XPoet/hexo-theme-keep#22]
categories页面也创建了，页面也能打开，文章的分类页指定了，但是点击categories，页面内容是空白的
categorie的index.md如下：
---
title: 分类
date: 2020-11-01 20:34:59
type: "categories"
---

文章的分类指定如下：
---
title: Retrofit视频教程，实战开发
date: 2020-11-01 20:31:40
tags: http okhttp retrofit retrofit视频教程
categories: Retrofit
---
这样的配置有问题吗？请回复下，谢谢

**Comment by XPoet** [comment]
@mxdldev 

你这个写法有误，要加中括号和逗号（切换至英文输入法）
```
title: Retrofit视频教程，实战开发
date: 2020-11-01 20:31:40
tags: http okhttp retrofit retrofit视频教程
categories: Retrofit
```

改成这样就可以了：
```
title: 分类
date: 2020-11-01 20:34:59
```

```
title: Retrofit视频教程，实战开发
date: 2020-11-01 20:31:40
tags: [http, okhttp, retrofit, retrofit视频教程]
categories: [Retrofit]
```

**Comment by mxdldev** [comment]
> @mxdldev
> 
> 你这个写法有误，要加中括号和逗号（切换至英文输入法）
> 
> ```
> title: Retrofit视频教程，实战开发
> date: 2020-11-01 20:31:40
> tags: http okhttp retrofit retrofit视频教程
> categories: Retrofit
> ```
> 
> 改成这样就可以了：
> 
> ```
> title: 分类
> date: 2020-11-01 20:34:59
> ```
> 
> ```
> title: Retrofit视频教程，实战开发
> date: 2020-11-01 20:31:40
> tags: [http, okhttp, retrofit, retrofit视频教程]
> categories: [Retrofit]
> ```
我按照你的说法操作后，问题依旧啊，用的ILS V2.1.3 我感觉是不是你最新版的bug？

**Comment by XPoet** [comment]
**@所有人**

使用`hexo new page category` 命令创建的xxx页面 **title 不要修改！！**

上例正确的写法为：

```md
title: category 
date: 2020-11-01 20:34:59
```

文章页的 title 可以随便改
使用`hexo new post-xxxxx` 命令创建的文章 post-xxxxx 的 title 可以随便改。

**Comment by wohaoa** [comment]
@XPoet category按照你的设置可以了，但是tag还是不可以，显示如下
![image](https://user-images.githubusercontent.com/7288685/98313846-b2206d80-200f-11eb-95f1-77c3b9f42f80.png)

**Comment by XPoet** [comment]
@wohaoa 
这种情况是 `/source/` 目录下的文件不存在 `tags` 文件夹
你创建的页面是 tag 还是 tags ?
![image](https://user-images.githubusercontent.com/24516169/98315795-07f71480-2014-11eb-8650-117e11fe1dce.png)

请检查一下 `/source/` 目录下的文件夹，title 跟 `/source/` 目录下的文件夹名要一一对应。
使用命令 `hexo new page xxxx` 创建页面时，无需修改 title

**Comment by wohaoa** [comment]
@XPoet 确实是我这边创建有问题，是我创建的为tag而非tags导致，按你设置方式：
hexo new page xxxx 创建页面时，无需修改 title
可以正常显示分类页和标签页

**Comment by tivnan** [comment]
@wohaoa 你好，我也遇到了这个情况，无论我怎么设置，到最后我点击“categories”导航的时候，都是弹出一个空白页面，请问你是如何解决问题的呢？

**Comment by tivnan** [comment]
@XPoet 你好，我遇到了一个十分奇怪的问题
首先，我的确已经创建了一个`categories`页面，而且在`/source/`文件夹下也包含了这个页面
![Screenshot-20201213012750-309x421](https://user-images.githubusercontent.com/47658912/101990800-7a2dd980-3ce3-11eb-8f17-9a496d285902.png)
而这个页面的`index.md`文件如下编辑
![Screenshot-20201213012725-406x230](https://user-images.githubusercontent.com/47658912/101990821-93368a80-3ce3-11eb-87ba-c32f5b1890bc.png)
但是问题是，当我点开`categories`导航栏后，只能看到这个页面（我在`_post`文件夹下有写好且归类的文章）
![Screenshot-20201213013311-1297x326](https://user-images.githubusercontent.com/47658912/101990873-f32d3100-3ce3-11eb-84b9-464ec0b6cb81.png)

**Comment by dxf-keniula** [comment]
首先，分类的写法像下面这样其实都可以

// 这是默认的写法，给文章添加一个分类。
categories: 123

// 将文章分类123和456两个子目录下。
categories: [123, 456]

// 会将文章分类到123和456两个目录下。
categories:
   - 123
   - 456

// 多标签写法，文章被分类到123、456以及123的自分类789这3个分类下面，官方指定写法。
categories:
   - [123]
   - [456]
   - [123, 789]

其次，对于categories和tags页面下空白的解决方法，这里我们需要做的的就是，在categories/index.md下添加如下内容：

```
---
title: 文章分类
date: 2023-09-07 15:36:45
type: "categories"
---
```
即可解决了
