### ISSUE TITLE
请问如何修改顶部导航栏宽度？

### ISSUE THREAD

**Issue by UncleCAT4** [XPoet/hexo-theme-keep#220]
请问如何修改顶部导航栏宽度？我感觉这个“额头”有点大，请问如何进行修改

**Comment by XPoet** [comment]
暂时没有设置头部 Header 高度的配置项，你需要通过修改源码来实现。

**Comment by XPoet** [comment]
该功能已实现，请使用 `v3.8.5`，相关教程查看文档：
https://keep-docs.xpoet.cn/advanced/custom-style.html#%E5%AE%9A%E5%88%B6%E9%A1%B5%E9%9D%A2%E5%86%85%E5%AE%B9%E5%8C%BA%E5%9F%9F%E7%9A%84%E6%9C%80%E5%A4%A7%E5%AE%BD%E5%BA%A6

**Comment by XPoet** [comment]
![image](https://github.com/XPoet/hexo-theme-keep/assets/24516169/11737d8b-f888-46f4-828e-dd33a5a9f298)
