### ISSUE TITLE
文章插入表格

### ISSUE THREAD

**Issue by bigflya** [XPoet/hexo-theme-keep#221]
你好我将用typora 中含表格的文章上传后，无法显示表格，请问是主题目前没有适配还是不支持typora的表格

**Comment by XPoet** [comment]
Keep 主题支持 markdown ，当然也支持表格，只要你的 md 语法正确。

可以参考下这篇文章：

https://xpoet.cn/2017/10/%E5%BF%AB%E9%80%9F%E6%8E%8C%E6%8F%A1Markdown%E5%9F%BA%E7%A1%80%E8%AF%AD%E6%B3%95/#%E8%A1%A8%E6%A0%BC
