### ISSUE TITLE
求助脚注功能-问题有关hexo的markdown解析

### ISSUE THREAD

**Issue by Lyndon-wong** [XPoet/hexo-theme-keep#23]
我在win上的typora上编辑的文档是支持“悬浮脚注”的，这样的脚注一些小概念很方便理解，但是在hexo上脚注不支持这样的功能。我将hexo的markdown解析器插件替换为了hexo-renderer-markdown-it，但是还是不行
实在没办法了，所以求助如何实现一下这样的脚注功能，感谢！
[![imgbed.cn图床](https://vkceyugu.cdn.bspapp.com/VKCEYUGU-imgbed/295dbef7-c5a6-471e-bc27-62a2011d29d2.png)](https://imgbed.cn)

**Comment by Lyndon-wong** [comment]
![QQ截图20201105165257](https://user-images.githubusercontent.com/61778596/98219270-bf921500-1f87-11eb-96a0-00e17b2c6ea8.png)
类似与这种效果，方面了解某些小概念
我的网站链接是wanglindong.com

**Comment by XPoet** [comment]
@Lyndon-wong 
很实用的功能。目前 ILS 主题不支持这一显示方式，我研究一下，抽空加上

**Comment by Lyndon-wong** [comment]
谢谢您，十分感谢！

**Comment by XPoet** [comment]
有 Hexo 插件可以实现这一功能，主题不再额外开发改功能
