### ISSUE TITLE
[BUG] 页面顶部出现代码

### ISSUE THREAD

**Issue by Zhou-Shilin** [XPoet/hexo-theme-keep#230]
页面顶部出现代码
![58880400-7EFB-4A65-BB6E-4C717FCDF80F](https://github.com/XPoet/hexo-theme-keep/assets/86581525/8f2c9ae2-e12b-46bd-a51e-4034fef870db)
![912E2526-84F7-4859-A79D-AD4927302DCA](https://github.com/XPoet/hexo-theme-keep/assets/86581525/8c3763cd-c267-4ea7-89e3-f1db2f90084e)
文章上面也是一样
![4C1F8384-875C-463B-B43F-C74A6EBE6148](https://github.com/XPoet/hexo-theme-keep/assets/86581525/95480bad-1c88-4612-a68f-8e6e2ca193e5)

**Comment by XPoet** [comment]
请提供：

操作系统及版本
浏览器及版本
Node.js 版本
Hexo 版本
Keep 主题版本

复现步骤：
1、 ...
2、...

**Comment by Zhou-Shilin** [comment]
抱歉，clear后重新生成已修复
