### ISSUE TITLE
[BUG] 第一次访问时评论加载不出来，刷新后才正常

### ISSUE THREAD

**Issue by cnmoe** [XPoet/hexo-theme-keep#231]
站点：https://xpoet.cn/
复现路径：无访问记录的浏览器，访问站点，点🐔任意文章即出现
故障截图
![QQ截图20230624163245](https://github.com/XPoet/hexo-theme-keep/assets/119575222/929aa396-88aa-43ed-8d2d-fd9270634578)

**Comment by cnmoe** [comment]
) 应该不是 Waline 的问题吧 ~

**Comment by cnmoe** [comment]
）应该不是 Waline 的问题吧 ~

**Comment by XPoet** [comment]
无法复现。我在 Chrome 浏览器和 Edge 浏览器上清空了所有缓存，依旧无法复现。
可能是你当时的网络情况不佳， 我先关闭该 Issue，后续问题复现后再开启。

**Comment by LUKECLEVER** [comment]
https://github.com/XPoet/hexo-theme-keep/assets/60529895/9c274dae-e0d8-4f25-a0bc-abb69452dd77


我也遇到了这个问题，并且在Edge浏览器InPrivate模式下复现了该问题。

# 复现过程：
打开InPrivate页面（类似无痕浏览模式），访问使用Keep主题的站点，如 [本人站点](https://www.luyaoguagua.top/) ，然后点击任意文章。

# 问题出现：
评论区不加载，其中排除CDN无法访问问题，已经将评论区代码部署到个人服务器。
在当前页面刷新后，评论区正常加载。

# 尝试：
若[直接访问文章页面](https://www.luyaoguagua.top/Code/stapi-imapi-background)，而不是从主页点击文章后PJAX加载，评论区亦正常加载。

# 调试信息：
Keep v3.6.1
Twikoo v1.6.15
开启PJAX
关闭CDN
评论区加载代码 https://codes.luyaoguagua.top/js/twikoo.all.min.js
