### ISSUE TITLE
[功能建议] ICP备案号自定义跳转链接的配置项 和 Waline更多组件属性的配置项

### ISSUE THREAD

**Issue by cnmoe** [XPoet/hexo-theme-keep#232]
ICP备案号自定义跳转链接，希望加入能够自定义跳转链接的配置项。例如萌备： https://icp.gov.moe

Waline客户端组件属性，Waline还有好多可以自定义的组件属性，希望加入能够更多自定义的配置项。例如： https://waline.js.org/reference/client/props.html

**Comment by XPoet** [comment]
该 issue 提到的两个功能均已实现，请使用 `v3.8.5` 及以上版本。

1、ICP 自定义跳转链接配置，参考文档：
https://keep-docs.xpoet.cn/basis/configuration-guide/footer.html#url

2、Waline 评论插件组件属性扩展配置，参考文档：
https://keep-docs.xpoet.cn/basis/configuration-guide/comment.html#options
