### ISSUE TITLE
功能建议：可选默认暗色主题

### ISSUE THREAD

**Issue by LUKECLEVER** [XPoet/hexo-theme-keep#233]
请问有什么方法可以在初次打开网站就默认显示为暗色主题而不需要从右下角的功能菜单内选择嘛？

希望增加一个网站默认为暗色或是亮色的配置项。

![image](https://github.com/XPoet/hexo-theme-keep/assets/60529895/fc228def-7f65-4509-ae2f-1b6ae82e91d9)

**Comment by LUKECLEVER** [comment]
https://github.com/XPoet/hexo-theme-keep/issues/231#issuecomment-1666369385

😂同时我也注意到了评论区无法加载问题

**Comment by XPoet** [comment]
Keep 主题的模式设置规则：
1、判断你是否手动点击设置过暗/亮模式，如果有，用你的手动设置。
2、如果没有过手动设置，那么根据你的系统来自动设置。
