### ISSUE TITLE
（有争议，欢迎大家来测试）有一个bug持续好久了，你们都没发现吗？

### ISSUE THREAD

**Issue by SJH090** [XPoet/hexo-theme-keep#238]
返回顶部功能有bug

点击返回顶部按钮后，无论滑轮还是鼠标拖动侧边滚动条，网页整体抽搐

测试chrome和火狐都有这种情况

**Comment by XPoet** [comment]
换台好几台电脑测试，都无法复现，该问题暂时无法处理

**Comment by XPoet** [comment]
按你提供的步骤又测试了很多遍，依然无法复现这个问题。

建议你找其他电脑再试一下，有可能是你的鼠标滚动有问题。

这不是 Keep 主题的 Bug，我自己使用 Keep 好几年都没出现过这个问题。

**Comment by XPoet** [comment]
Keep 主题 `v3.8.0` 已发布，该问题已得到优化，请使用最新版本。
