### ISSUE TITLE
【重要通知】原 Hexo 主题 ILS 改名 Keep

### ISSUE THREAD

**Issue by XPoet** [XPoet/hexo-theme-keep#25]
自 `v3.0.0` 起，原Hexo 主题 ILS 已改名 **Keep**。
**Keep** 在 ILS 基础上做了大量改进、优化和代码重构，全新设计、全面提升、更轻、更快。
希望你积极提出反馈及建议。

**Comment by 16fly** [comment]
新主题 Keep 漂亮！
