### ISSUE TITLE
3.7.7版本 使用hexo g 命令, 提示CSS内容报错

### ISSUE THREAD

**Issue by cemonliu** [XPoet/hexo-theme-keep#251]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version 3.7.3 or later.
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn/tutorial/get-start/install-theme.html).
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me.

### Expected behavior | 预期行为

完整运行

### Actual behavior | 实际行为

![image](https://github.com/XPoet/hexo-theme-keep/assets/42933407/1e540d10-7be5-40c5-9b1f-df57f2fbd946)
cannot perform $component-spacing-value * 0.8

### Steps to reproduce the behavior | 重现步骤

1. First step ...
2. Second step ...
3. Third step ...

### Node.js and NPM Information | Node.js 和 NPM 信息

```Text
e:\Blog>node -v && npm -v
v18.17.1
10.1.0
```

### Hexo Configuration | Hexo 配置

```YAML
使用默认config文件一样报错
```

### Keep Configuration | Keep 配置

```YAML
未修改
```

**Comment by XPoet** [comment]
你提供的信息不详细，无法复现你的环境。
这样，你使用 Keep 主题启动模板运行一下，看看会不会报错。
https://keep-docs.xpoet.cn/tutorial/get-start/quick-starter.html

**Comment by cemonliu** [comment]
用启动模板也测试了下，不是环境问题。发现问题在一篇文章里。之前旧版本没有报错。

---
title: PowerBI KPI card实现
date: 2023-08-28_10:33:28
categories: 技术分享
tags: 
---
## KPI多行card的实现
>针对TOP N的销售额去排列展示，并且分为按Sub catgory , model, sku展示不同的Rank ,成品图如下 

![](https://cdn.jsdelivr.net/gh/cemonliu/blogpic/202308281407549.png)

### 图形界面的展示方式
目前实现的方式有两种。比较友好的方式是采用第二种（应该也是后期更新的）
1. 使用inforgraphic Designer插件 
这个插件的功能太过于强大。上图中最右边的即使用该插件来完成的。在使用该Visual时，可以删除默认图表，然后进行二次编辑。同时创建文本并且绑定相应的值。这里放了两个文本，这些文本本身还可以采用layout进行位置的设定。所以功能强大但是有点操作复杂。
![](https://cdn.jsdelivr.net/gh/cemonliu/blogpic/202308281419664.png)

2. 使用新的visual KPI multicard
左边的三个卡片都是使用官方后期新增的visual来实现，整体样式也比较好。方法一如果设定不好会导致字体被遮挡的问题。而此方法则不存在这个问题。简单的将两个数据拖到图表里面就可以。



### DAX公式学习
公式一：
将t设定为前段slicer的选择topn对应的序号，
然后判定相应的排名，如果排名低于选择的序号，则展示销售金额，否则显示空。
同时在view界面展示时使用filter将空值隐藏掉
```dax
销售金额_top = var t  =SELECTEDVALUE('Topn'[序号])
Return IF([Rank_按营业额]<=T,[销售金额],BLANK())
```

公式二：
判断筛选的是产品的哪一列，如果是subcategory,则针对subcategory进行按照销售金额进行排名，其他的按照model,产品，以及sku相应的进行排名。
```dax
Rank_按营业额 = VAR RESURT = SWITCH(TRUE(),ISFILTERED('Product'[Subcategory]), RANKX(ALLSELECTED('Product'[Subcategory]),[销售金额]),
                    ISFILTERED('Product'[Model]),RANKX(ALLSELECTED('Product'[Model]),[销售金额]),
                    ISFILTERED('Product'[Product]), RANKX(ALLSELECTED('Product'[Product]),[销售金额]),
                    ISFILTERED('Product'[SKU]), RANKX(ALLSELECTED('Product'[SKU]),[销售金额]),
                    BLANK())
                RETURN RESURT
```




## 图表绘制databar实现

使用两个相同的度量值，将数据显示同一个矩阵里面。同时，将后面一个的数据使用databar来展示，这样就可以显示出来相应的柱状图效果。
**对于汇总的数据可以在row subtotals里面针对不同的level等级进行设置。**

![](https://cdn.jsdelivr.net/gh/cemonliu/blogpic/202308281548192.png)

**在勾选时需要注意选择show bar only.**
![](https://cdn.jsdelivr.net/gh/cemonliu/blogpic/202308281604248.png)



## 成品图形
> 中间的部分逻辑比较简单就不用再研究。是环形图搭配multirow card来实现。

![](https://cdn.jsdelivr.net/gh/cemonliu/blogpic/202308281608942.png)

**Comment by cemonliu** [comment]
> 你提供的信息不详细，无法复现你的环境。 这样，你使用 Keep 主题启动模板运行一下，看看会不会报错。 https://keep-docs.xpoet.cn/tutorial/get-start/quick-starter.html

模板最初运行正常，我的一个文件运行问题。然后当文件删除后，再运行也有问题了
[PowerBI记录230828.md](https://github.com/XPoet/hexo-theme-keep/files/12710693/PowerBI.230828.md)

**Comment by XPoet** [comment]
我创建了你的文章，执行 `hexo g` 没有问题，可以正常编译构建。

建议你先执行 `hexo clean` 清除下旧的缓存，再执行 `hexo g`，如果还有问题，你需要把你完整的 hexo 项目文件发我排查

**Comment by cemonliu** [comment]
> 我创建了你的文章，执行 `hexo g` 没有问题，可以正常编译构建。
> 
> 建议你先执行 `hexo clean` 清除下旧的缓存，再执行 `hexo g`，如果还有问题，你需要把你完整的 hexo 项目文件发我排查

执行了还是不行，附件是启动模板 我放了上面会报错的文件后，就会一直报错了。 谢谢
[hexo-theme-keep-starter-main-1.zip](https://github.com/XPoet/hexo-theme-keep/files/12712771/hexo-theme-keep-starter-main-1.zip)

**Comment by cemonliu** [comment]
我测试了下， 把这两个变量放到article-content.styl文件里面就不会报错了。
$component-spacing-value = 38px                                 // component-spacing-value (PC)
$content-max-width = 928px                                      // main content max width

**Comment by XPoet** [comment]
该问题已得到修复，即将发布在 `v3.8.0` 。

**Comment by XPoet** [comment]
Keep 主题 `v3.8.0` 发布，请使用最新版本。
