### ISSUE TITLE
作者头像怎么修改，目前是默认你的头像

### ISSUE THREAD

**Issue by markruan** [XPoet/hexo-theme-keep#27]
查了下，默认CDN 链接的，怎么修改，谢谢

**Comment by XPoet** [comment]
@markruan 

感谢反馈问题，这是我在主题开发设计上的失误，等会紧急修复。

第一种方法：在主题配置文件 _config.yml 里关闭 CDN，将 `enable` 设置为 false
```yml
cdn:
  enable: false
```

第二种方法：需要修改源码

找到 `themes/keep/layout/article-content.ejs` 文件
找到 第 11 行代码，将 ` __image_tag` 修改为 `image_tag`

参考如下：
```html
<div class="avatar">
    <%- image_tag('images/avatar.png') %>
</div>
```

**这两种方法都需要你将 `themes/keep/source/images/avatar.png` 路径的 avatar.png 图片替换成你自己的图片**

**Comment by XPoet** [comment]
该 bug 已紧急修复。
请使用 master 分支最新代码：
```
git clone --depth=1 https://github.com/XPoet/hexo-theme-keep themes/keep
```

**Comment by markruan** [comment]
我刚才用了2.X修复了，可以在设置里修改

**Comment by XPoet** [comment]
3.x 跟 2.x 版本有较大的改动，建议使用最新版，只需把你主题配置文件的配置项填在 3.x 里即可

**Comment by markruan** [comment]
我就改了两个有问题地方的代码，整体还是3.X, 你的主题我很喜欢谢谢。有时间我再更新下

**Comment by Kyson** [comment]
找了一圈文档没找到怎么修改头像，3.4.0的版本，这个有文档吗？另外希望可以贴一个全部配置的文档 @XPoet

**Comment by Kyson** [comment]
@XPoet 从node_modules的theme里找到了，不过你的博客和theme里的配置有些已经变了，更新一下博客吧

**Comment by XPoet** [comment]
@Kyson 
新的Keep主题使用文档，正在撰写中，解决发布
