### ISSUE TITLE
了解下文章内部跳转的问题

### ISSUE THREAD

**Issue by LuXugang** [XPoet/hexo-theme-keep#270]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version 3.8.5 or later.
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn).
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me.

### Other Information | 其它信息

原生的html网页支持文章内部标题的跳转，例如 有两个标题   
# 标题1     

## 标题2
可以通过 [跳转标题1](#标题1)    [跳转标题2](##标题2) 的方式进行标题跳转 请问支持吗 谢谢~

**Comment by XPoet** [comment]
支持的，你需要在 Markdown 中填写相对路径。
例如：你有文章 1 （路径 `_post/2023/1.md`）、和文章 2（路径 `_post/2023/2.md`）
在文章 1 中填写跳转文章 2 ，写法：`[文章 2](/2023/2)`

这跟 Keep 主题没有本质的关系。

**Comment by LuXugang** [comment]
谢谢作者
