### ISSUE TITLE
网易云音乐 iframe 功能在手机端失效问题

### ISSUE THREAD

**Issue by DonTequilaaa** [XPoet/hexo-theme-keep#272]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version 3.8.5 or later.
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn).
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me.

### Expected behavior | 预期行为

今年一月初，在文章内放置 wyy 的 iframe 外链播放器一切正常，iOS 和 Windows 显示均正常，可以播放，也不会显示空白

### Actual behavior | 实际行为

一段时间后，IOS 手机与 iPad 端在 safari 和别的浏览器上的外链统统失效，原本的位置变成了空白，点击也没有任何显示
电脑端正常。但是在手机浏览器设置中，调为“”为此网站适配电脑端显示“”，可以显示成功，但是整体美观又会受到影响

### Steps to reproduce the behavior | 重现步骤

1.正常操作打开网页
2.进入嵌有 wyy iframe 的文章页面
3.显示空白

### Node.js and NPM Information | Node.js 和 NPM 信息

```Text
1
```

### Hexo Configuration | Hexo 配置

```YAML
1
```

### Keep Configuration | Keep 配置

```YAML
1
```

### Other Information | 其它信息

ios 自带 safari 和 Google Chrome

**Comment by XPoet** [comment]
这个问题跟 Keep 主题本身没有直接的关系，作者也难于帮你排查。
可能是网易云音乐的外链播放器突然增加了限制移动端访问，建议你咨询网易云音乐的客服

**Comment by bianyukun1213** [comment]
网易云音乐外链 iframe 在移动端下会重定向到 HTTP 页面，而非 HTTPS 页面，因此无法加载。可以写一个 Injector 注入修复脚本，在修复脚本中判断当前是否是移动端，如果是移动端，就把 `music.163.com/` 替换为 `music.163.com/m/`。经手动替换后，协议保持 HTTPS 不变，经测试外链页面可以正常加载。
