### ISSUE TITLE
标题名能否自动为文件的名字呢？如果没有 title 的情况下

### ISSUE THREAD

**Issue by Fierygit** [XPoet/hexo-theme-keep#29]

**Comment by XPoet** [comment]
目前不支持，因为会存在 **文件名** 跟 **标题名** 不一致的情况。
你用命令 `hexo new "post title"` 创建文章时，会自动生成 title 。

![image](https://user-images.githubusercontent.com/24516169/101300189-b5598400-386f-11eb-8d8b-d02ca44d4459.png)

如果没有 title 或 title 为空值，那页面上也不会显示文章标题，建议加上 title 。
