### ISSUE TITLE
咨询一个关于代码块设置的问题

### ISSUE THREAD

**Issue by seedscoder** [XPoet/hexo-theme-keep#294]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.0.5` or later. （使用 Keep `4.0.5` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Other Information | 其它信息

当代码块的内容过长的时候，请问可以设置代码块默认为非折叠状态吗？ 

<img width="845" alt="image" src="https://github.com/XPoet/hexo-theme-keep/assets/34568397/af87b873-585b-44eb-b37f-624632f016e8">

**Comment by XPoet** [comment]
当代码块内容过长时，影响阅读体验，默认会自动折叠一部分。暂不支持设置，后续版本会考虑加上。

**Comment by seedscoder** [comment]
了解🫡
