### ISSUE TITLE
background color for ":root" wont change when toogle-theme button clicked [at least in firefox]

### ISSUE THREAD

**Issue by justaLoli** [XPoet/hexo-theme-keep#295]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.0.5` or later. （使用 Keep `4.0.5` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Expected behavior | 预期行为

页面到顶，继续向下拉；或者页面到底，继续向下拉。
拉出来的部分的背景颜色会和网页的背景颜色不同。
![CleanShot 2023-12-28 at 18 55 46](https://github.com/XPoet/hexo-theme-keep/assets/92238102/f8fa308c-3063-4cd4-9416-8b8e8090ce67)
![CleanShot 2023-12-28 at 18 56 11](https://github.com/XPoet/hexo-theme-keep/assets/92238102/8daa843d-ed3c-4d81-b9b3-fba10e3b219c)

问题会出现在：系统是日间模式，但手动设置了夜间模式；系统是夜间模式，但手动设置夜间模式的情况。
我只在mac的firefox上出现了这个问题。如果您无法复现或无法处理这个问题，请联系我。

### Actual behavior | 实际行为

-

### Steps to reproduce the behavior | 重现步骤

-

### Node.js and NPM Information | Node.js 和 NPM 信息

```Text
firefox v121
```

### Hexo Configuration | Hexo 配置

```YAML
nothing
```

### Keep Configuration | Keep 配置

```YAML
nothing
```

### Other Information | 其它信息

firefox v121
mac

**Comment by XPoet** [comment]
感谢反馈，下一个版本将会优化此问题

**Comment by XPoet** [comment]
该问题已解决，请使用 `4.0.6` 及以上版本

**Comment by justaLoli** [comment]
好耶，谢谢
