### ISSUE TITLE
分类页面，分类条目显示方式或者点击范围优化

### ISSUE THREAD

**Issue by witqu** [XPoet/hexo-theme-keep#299]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.0.5` or later. （使用 Keep `4.0.5` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Feature Request | 功能需求

1、需求描述：分类页面分类条目可点击范围有点小，只能点击标题文字，特别是是在手机上操作不方便。可以优化为
方式1：以“分类文字+数量”的形式显示为按钮，并且修改布局，一页显示更多分类按钮，详见参考链接
方式2：不修改布局，修改点击范围，把分类条目的一行设置为可点击

2、参考链接：
方式1参考链接：http://blinkfox.com/categories
方式2参考链接：https://spaceskynet.top/categories/

3、参考截图：
方式1：
![image](https://github.com/XPoet/hexo-theme-keep/assets/7465879/61054f04-81f8-4c37-a44d-4333c6c005c7)
方式2:
![image](https://github.com/XPoet/hexo-theme-keep/assets/7465879/11180ab9-0d3a-4fd8-8278-2ebe3a52c716)

**Comment by XPoet** [comment]
该 Issue 反馈的问题已在 `v4.0.7` 得到优化。

同时 Keep 的分类页面支持多级分类：

<img width="1092" alt="image" src="https://github.com/XPoet/hexo-theme-keep/assets/24516169/363125c8-d1ed-44c1-b5be-46eaeb3dedba">
