### ISSUE TITLE
移动端首页文章列表点击会自动缩小

### ISSUE THREAD

**Issue by markruan** [XPoet/hexo-theme-keep#30]
移动端首页文章列表点击会自动缩小

**Comment by XPoet** [comment]
经我测试，移动端首页文章列表标题点击时并没发现自动缩小。
麻烦提供下你的操作系统，浏览器版本。

**Comment by markruan** [comment]
x.iqimeng.com
是不是版本的问题？

**Comment by XPoet** [comment]
@markruan 确实是 Keep 主题的 bug，style.hover.scale 开启时，移动端没优化好。
下个版本修复 这个 bug。
感谢反馈~

**Comment by XPoet** [comment]
看你的博客对 Keep 二次修改的很好，欢迎参与贡献代码 🤝

**Comment by markruan** [comment]
> 看你的博客对 Keep 二次修改的很好，欢迎参与贡献代码 🤝

瞎改改的，代码有些乱不好意思提交，主要是添加了particles.js，加在了first-screen.ejs里面
`<script src="/js/particles.min.js"></script>
<div class="first-screen-container flex-center ">
    <div class="content flex-center">
        <div class="description">
            <%= theme.style.first_screen.description || config.description %>
        </div>
        <% if (theme.social_contact.enable) { %>
            <ul class="s-icon-list">
                <% for (const key in theme.social_contact.links) { %>
                    <% if(theme.social_contact.links[key]) { %>
                        <% if(key === 'email') { %>
                            <li class="s-icon-item <%= key %>">
                                <a href="mailto:<%- url_for(theme.social_contact.links[key]) %>">
                                    <i class="fas fa-envelope"></i>
                                </a>
                            </li>
                        <% } else { %>
                            <li class="s-icon-item <%= key %>">
                                <a href="<%- url_for(theme.social_contact.links[key]) %>">
                                    <i class="fab fa-<%= key %>"></i>
                                </a>
                            </li>
                        <% } %>
                    <% } %>
                <% } %>
            </ul>
        <% } %>
    </div>
</div>
<canvas class="background" style="width: 100%; " ></canvas>
<style>
 .background{
    background-color: #fffff;
    width: 100%; 
    position: absolute;
    display: block;
    top: 0;
    left: 0;
    z-index: 0;
 }
 .first-screen-container{
 
   z-index:1000
 }
</style>
<script> 
    window.onload = function() {
        Particles.init({
          selector: '.background',
          color: '#75A5B7',
          maxParticles: 100,
          connectParticles: true,
          responsive: [
            {
              breakpoint: 768,
              options: {
                maxParticles: 80
              }
            }, {
              breakpoint: 375,
              options: {
                maxParticles: 50
              }
            }
          ]
  });
};
    
</script>`
