### ISSUE TITLE
文章详情页-发布时间，更新时间的图标可配置

### ISSUE THREAD

**Issue by witqu** [XPoet/hexo-theme-keep#301]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.0.5` or later. （使用 Keep `4.0.5` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Feature Request | 功能需求

文章详情页-发布时间，更新时间的图标可配置

**Comment by XPoet** [comment]
该 Issue 所提到的功能已在 `v4.1.0` 实现，请使用最新版本的 Keep 主题。

具体使用方式，请查看文档：
https://keep-docs.xpoet.cn/basis/configuration-guide/post.html#created-datetime-icon
