### ISSUE TITLE
详情页-文章标题下可的作者名称，可配置是否显示/隐藏。隐藏后标题和发布时间的间距需调整

### ISSUE THREAD

**Issue by witqu** [XPoet/hexo-theme-keep#302]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.0.5` or later. （使用 Keep `4.0.5` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Feature Request | 功能需求

详情页-文章标题下可的作者名称，可配置是否显示/隐藏。隐藏后标题和发布时间的间距需调整

**Comment by XPoet** [comment]
`v4.0.7` 已支持隐藏文章内容页的作者名称，使用教程参考 [官方文档](http://localhost:5174/advanced/custom-style.html#%E9%9A%90%E8%97%8F%E6%96%87%E7%AB%A0%E5%86%85%E5%AE%B9%E9%A1%B5%E9%9D%A2%E4%BD%9C%E8%80%85%E5%90%8D%E7%A7%B0)
