### ISSUE TITLE
标签页面，可设置彩色标签模式

### ISSUE THREAD

**Issue by witqu** [XPoet/hexo-theme-keep#303]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.0.5` or later. （使用 Keep `4.0.5` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Feature Request | 功能需求

标签页面，可设置彩色标签模式

**Comment by XPoet** [comment]
Keep `v4.1.2` tags 页面支持另一种显示方式。

![image](https://github.com/XPoet/hexo-theme-keep/assets/24516169/a0f57416-1622-4c12-8eb4-4f044ae26424)

详情参考文档：
https://keep-docs.xpoet.cn/advanced/page-config.html#tag-cloud
