### ISSUE TITLE
部署失败，提示证书失效

### ISSUE THREAD

**Issue by WhenCoding** [XPoet/hexo-theme-keep#304]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.0.5` or later. （使用 Keep `4.0.5` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Expected behavior | 预期行为

正常部署

### Actual behavior | 实际行为

错误信息提示如图所示：
![Xnip2024-01-23_10-29-05](https://github.com/XPoet/hexo-theme-keep/assets/28731024/cbf69938-abd8-4a76-83f4-4398a71cb696)
github action如图所示：
![Xnip2024-01-23_10-29-30](https://github.com/XPoet/hexo-theme-keep/assets/28731024/6a69910d-a90b-4bdb-9a99-7280f37fbccd)

### Steps to reproduce the behavior | 重现步骤

如图

### Node.js and NPM Information | Node.js 和 NPM 信息

```Text
如图
```

### Hexo Configuration | Hexo 配置

```YAML
如图
```

### Keep Configuration | Keep 配置

```YAML
如图
```

### Other Information | 其它信息

如图

**Comment by WhenCoding** [comment]
已经将本地的package-lock.json清除不使用淘宝的镜像源也是不行

**Comment by XPoet** [comment]
1、你使用 theme-keep/hexo-deploy-github-pages-action 遇到问题，那就到 [theme-keep/hexo-deploy-github-pages-action](https://github.com/theme-keep/hexo-deploy-github-pages-action) 上提 Issue。
2、theme-keep/hexo-deploy-github-pages-action 正常可用，看到你 https://github.com/WhenCoding/WhenCoding.github.io 你在 4 小时前还成功部署。
3、你本地删除 package-lock.json 后，还需要 push。
4、如果遇到部署失败情况，可以在 github Actions 页面点击重新运行 actions。

**Comment by WhenCoding** [comment]
好的，明白，多谢，果然是package-lock.json的问题。
