### ISSUE TITLE
文本中代码高亮遇到的问题

### ISSUE THREAD

**Issue by isbutch** [XPoet/hexo-theme-keep#311]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.1.0` or later. （使用 Keep `4.1.0` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Other Information | 其它信息

问题如图所示：
莫名其妙多了一个border、回退主题色没能解决。（呜呜 别介意我的愚蠢 没能自己解决
![01](https://github.com/XPoet/hexo-theme-keep/assets/67615927/d4fb546b-6c78-4810-80e1-609d2ad1d279)
![02](https://github.com/XPoet/hexo-theme-keep/assets/67615927/e52f5c66-8527-4058-aa5b-61df5df7421e)

**Comment by XPoet** [comment]
这是主题内置的代码块效果。

```
如果给代码加了 ``（例如：`code`） 就会有这种效果
```

<img width="895" alt="image" src="https://github.com/XPoet/hexo-theme-keep/assets/24516169/f288e8c3-8e40-417a-8d57-33cd425967b5">

**Comment by XPoet** [comment]
如果你不想要这种内置的默认效果，可以使用注入 CSS 的方式来去除。

参考文档：
https://keep-docs.xpoet.cn/basis/configuration-guide/inject.html#css

CSS：
```css
code {
  border: none;
}
```

**Comment by isbutch** [comment]
- 真是抱歉，我没注意到这个是默认的高亮效果、有看说明文档 但是也略过了这块有点难度的内容。🥲ps:主题预览我这边打开有点慢(已科学上网 ，不清楚是不是我的网络状况。
- **感谢大佬给出的解决方案，已经完美解决问题啦。😁（**
