### ISSUE TITLE
请问可以设置多个作者吗

### ISSUE THREAD

**Issue by muxinxy** [XPoet/hexo-theme-keep#312]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.1.0` or later. （使用 Keep `4.1.0` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Feature Request | 功能需求

- Detailed description of feature request （功能需求的详情描述）
设置多个作者，每篇文章可以显示不同作者
- This feature request reference link （功能需求的参考链接）
- This feature request reference screenshots （功能需求的参考截图）

**Comment by XPoet** [comment]
支持，参考 [文档教程](https://keep-docs.xpoet.cn/writing/front-matter.html#%E8%AE%BE%E7%BD%AE%E6%96%87%E7%AB%A0%E7%9A%84%E4%BD%9C%E8%80%85%E5%90%8D%E7%A7%B0)

**Comment by muxinxy** [comment]
感谢
