### ISSUE TITLE
footer底部加入 公网安备的备案号

### ISSUE THREAD

**Issue by chrisdong** [XPoet/hexo-theme-keep#316]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.1.0` or later. （使用 Keep `4.1.0` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Feature Request | 功能需求

主题footer中有icp 但没有公网安备的 备案信息，能否加入

**Comment by XPoet** [comment]
该需求已支持，请使用 `v4.1.2`。详情参考文档：https://keep-docs.xpoet.cn/basis/configuration-guide/footer.html#record

![image](https://github.com/XPoet/hexo-theme-keep/assets/24516169/8a215a5e-af84-4762-b5a4-5fd5d4452817)
