### ISSUE TITLE
文字高亮

### ISSUE THREAD

**Issue by Wu-Jackie** [XPoet/hexo-theme-keep#317]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.1.0` or later. （使用 Keep `4.1.0` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Feature Request | 功能需求

- Detailed description of feature request （功能需求的详情描述）
我习惯在typora进行写作，在这个软件中使用\=\=会高亮，如下图
![image](https://github.com/XPoet/hexo-theme-keep/assets/108189073/6eda3efc-8c16-4777-b4fb-1efebd5e38d2)
而我上传到博客中却无法按照我的预期呈现出理想的样式
![image](https://github.com/XPoet/hexo-theme-keep/assets/108189073/f083134d-aed9-46b1-9f3e-22af56ca1a19)
希望作者可以添加这个简单的小功能

### Other Information | 其它信息

正如`Feature Request | 功能需求`中的图二所示，下面两个我使用了\`\`达到了高亮的效果，但是遗憾的是在typora的默认主题（GitHub）中它的样式发灰，无法有高对比度，故我更喜欢使用\=\=，同时我也明白可以使用html语句，但正如您的功能文档所提到的：把时间放在内容创作上，而无需再花费额外的精力在样式上（这也是我非常喜欢您这款主题的原因:p），希望作者可以考虑增加这个实用的功能♡

**Comment by XPoet** [comment]
`===` 不是标准的 Markdown 语法，后续看看有没有其他解决方案

**Comment by Wu-Jackie** [comment]
今日因Latex渲染问题按照此[issue](https://github.com/XPoet/hexo-theme-keep/issues/215#issuecomment-1678608555)更换了渲染器，发现高亮问题一并解决，在此留档
