### ISSUE TITLE
希望归档页面能设置成下拉式，翻页式需要加载且不够直观

### ISSUE THREAD

**Issue by R3damancy1** [XPoet/hexo-theme-keep#318]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.1.0` or later. （使用 Keep `4.1.0` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Feature Request | 功能需求

- Detailed description of feature request （功能需求的详情描述）
- This feature request reference link （功能需求的参考链接）
- This feature request reference screenshots （功能需求的参考截图）

**Comment by XPoet** [comment]
归档页属于时间轴的表现形式，不适合做成折叠效果，该需求暂时不做处理。
