### ISSUE TITLE
Waline V3 Client更新了JS引入方式，希望能够更新Waline插件

### ISSUE THREAD

**Issue by tyadan** [XPoet/hexo-theme-keep#322]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.1.0` or later. （使用 Keep `4.1.0` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Feature Request | 功能需求

<script type="module">
  import { init } from 'https://unpkg.com/@waline/client@v3/dist/waline.js';

  init({
    // options
  });
</script>
以上是waline v3的js引入方式，与v2和v1都不同，需要同步更新下，谢谢

**Comment by XPoet** [comment]
感谢反馈，下一版本将支持配置 Waline V3

**Comment by famousprince** [comment]
https://unpkg.com/@waline/client@v3/dist/waline.js 或 https://cdn.jsdelivr.net/npm/@waline/client@v3/dist/waline.js 能否换成  https://s4.zstatic.net/npm/@waline/client@3.1.3/dist/waline.js 这种国内加载速度比较好的 CDN 呢？

**Comment by XPoet** [comment]
已支持 Waline `v3`，请使用 Keep 主题 `v4.1.2`。
<img width="695" alt="image" src="https://github.com/XPoet/hexo-theme-keep/assets/24516169/1a52175b-6b10-4a6a-9879-54b0ce94ca0c">

**Comment by XPoet** [comment]
> https://unpkg.com/@waline/client@v3/dist/waline.js 或 https://cdn.jsdelivr.net/npm/@waline/client@v3/dist/waline.js 能否换成 https://s4.zstatic.net/npm/@waline/client@3.1.3/dist/waline.js 这种国内加载速度比较好的 CDN 呢？

下一版本会支持 cdnjs
