### ISSUE TITLE
使用 hexo-blog-encrypt 插件加密有TOC的文章

### ISSUE THREAD

**Issue by LUKECLEVER** [XPoet/hexo-theme-keep#323]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.1.0` or later. （使用 Keep `4.1.0` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Other Information | 其它信息

开发者您好，我阅读了Keep文档中关于[文章访问密码](https://keep-docs.xpoet.cn/writing/front-matter.html#%E8%AE%BE%E7%BD%AE%E6%96%87%E7%AB%A0%E8%AE%BF%E9%97%AE%E5%AF%86%E7%A0%81)的部分。在启用该插件后发现文章的TOC无法正常显示，查阅插件文档后发现需要[修改部分主题部分代码](https://github.com/D0n9X1n/hexo-blog-encrypt/blob/master/ReadMe.zh.md#%E5%AF%B9-toc-%E8%BF%9B%E8%A1%8C%E5%8A%A0%E5%AF%86)。想请教一下应该如何修改主题代码才能使TOC正常显示呢。

**Comment by XPoet** [comment]
下一版本会完善

**Comment by ydshi0** [comment]
好巧，我今天也需要这个功能。

**Comment by XPoet** [comment]
Keep 主题 `v4.1.2` 做了优化处理，现在加密文章能显示 TOC 了。
