### ISSUE TITLE
Footer在不打开访问统计的情况下，和备案号之间多出一个空行

### ISSUE THREAD

**Issue by tyadan** [XPoet/hexo-theme-keep#326]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.1.2` or later. （使用 Keep `4.1.2` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Feature Request | 功能需求

<img width="611" alt="image" src="https://github.com/XPoet/hexo-theme-keep/assets/13864360/7680bef7-4bdb-4bf7-8ff5-00dcfe404f6d">
如图所示，在关闭访问统计后，建议直接在count-info的div外层直接做判断屏蔽这个div的展示

**Comment by XPoet** [comment]
下一版本优化

**Comment by XPoet** [comment]
该 Issue 反馈的问题已在 `v4.1.3` 得到优化。请使用最新版本。
