### ISSUE TITLE
现在页面的主题颜色是根据系统颜色来判断显示的，是否可以指定默认颜色，而不是根据系统颜色来

### ISSUE THREAD

**Issue by hanjiangjiaolong** [XPoet/hexo-theme-keep#327]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.1.2` or later. （使用 Keep `4.1.2` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Feature Request | 功能需求

- Detailed description of feature request （功能需求的详情描述）
- This feature request reference link （功能需求的参考链接）
- This feature request reference screenshots （功能需求的参考截图）

### Other Information | 其它信息

现在页面的主题颜色是根据系统颜色来判断显示的，是否可以指定默认颜色，而不是根据系统颜色来

**Comment by XPoet** [comment]
点击右下角的工具按钮，可以切换白昼和暗夜模式。
<img width="164" alt="image" src="https://github.com/XPoet/hexo-theme-keep/assets/24516169/2f13005b-ec53-4522-8a6a-8d8bcccb6019"> | <img width="143" alt="image" src="https://github.com/XPoet/hexo-theme-keep/assets/24516169/5be5a018-bea9-47f4-a906-54f77e41b8ca">

**Comment by hanjiangjiaolong** [comment]
我需要在配置文件可以指定当前默认的颜色

**Comment by XPoet** [comment]
下个版本支持

**Comment by XPoet** [comment]
该需求已在 `v4.1.3` 实现，详情请查看文档：https://keep-docs.xpoet.cn/basis/configuration-guide/base_info.html#mode
