### ISSUE TITLE
希望把head部分优化下

### ISSUE THREAD

**Issue by mxdldev** [XPoet/hexo-theme-keep#33]
希望作者能把head部分优化下，博客都上线几个月了，尽然没有被百度，google收录

<!DOCTYPE html>
--
  | <html lang="zh-Hans">
  | <head>
  | <meta charset="utf-8">
  |  
  | <title>
  |  
  | 门心叼龙的个人博客
  | </title>
  | <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  |  
  | <link rel="shortcut icon" href="/images/favicon.png">
  |

**Comment by XPoet** [comment]
下一版本优化

**Comment by XPoet** [comment]
**`v3.3.2`** 及以上版本已对 head 部分进行优化，请使用最新版本。
