### ISSUE TITLE
代码高亮: diff 文件代码是否支持语法高亮

### ISSUE THREAD

**Issue by markyangcc** [XPoet/hexo-theme-keep#330]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.1.3` or later. （使用 Keep `4.1.3` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Feature Request | 功能需求

- diff 文件代码我使用过程发现好像不支持代码语法高亮，有办法配置 diff 文件支持语法高亮吗？

- 参考样例，
![image](https://github.com/XPoet/hexo-theme-keep/assets/60422898/28bade93-1c5a-4194-9ffb-93de243caa34)

**Comment by XPoet** [comment]
支持的，刚刚测试了，有点小问题，已修复，这两天内发布新版。
![image](https://github.com/XPoet/hexo-theme-keep/assets/24516169/26521548-9003-42f2-bb90-7afd59201438)

**Comment by markyangcc** [comment]
Thanks~

**Comment by XPoet** [comment]
该问题已处理，请使用 `v4.1.4` 。
