### ISSUE TITLE
tools页面内容较少时（不足一屏的情况） 点击侧导航顶部导航收起后就无法再出现

### ISSUE THREAD

**Issue by huabiyi** [XPoet/hexo-theme-keep#342]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.1.5` or later. （使用 Keep `4.1.5` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Expected behavior | 预期行为

tools内面内容不足一屏的情况下，点击侧导航，顶部导航不会收起，仍显示在页面上。或者在内容较少的情况下不出现侧导航呢？

### Actual behavior | 实际行为

- Links to demo site with this issue （链接到这个 Issue 的演示网站）
https://huabiyi.github.io/tools/

- Screenshots（屏幕截图）
![image](https://github.com/XPoet/hexo-theme-keep/assets/24467705/f4f4404c-d70a-4737-9d6f-8e1a454b1bbc)

### Steps to reproduce the behavior | 重现步骤

1.  页面加载完成之后，点击侧导航中的任何一项
2. 等待片刻，顶部导航就会收起来

### Node.js and NPM Information | Node.js 和 NPM 信息

```Text
v18.20.0
10.5.0
```

### Other Information | 其它信息

浏览器：Chrome126.0
操作系统：Windows 11

**Comment by XPoet** [comment]
已关注，下一版本修复

**Comment by XPoet** [comment]
该 Issue 反馈的问题已修复，请使用最新版本 `v4.2.0`。
