### ISSUE TITLE
 友链怎么加评论区啊

### ISSUE THREAD

**Issue by i7366464** [XPoet/hexo-theme-keep#343]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.1.5` or later. （使用 Keep `4.1.5` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Other Information | 其它信息

看了其它issue，没有找到解决方法

**Comment by XPoet** [comment]
查看文档：
https://keep-docs.xpoet.cn/advanced/page-config.html#comment

<img width="886" alt="image" src="https://github.com/XPoet/hexo-theme-keep/assets/24516169/b792634e-bbd1-47f0-8e86-240b813cbb4f">

**Comment by i7366464** [comment]
感谢感谢，不好意思，多有打扰。
