### ISSUE TITLE
打包的文件上传到服务器后，状态栏和文章打不开

### ISSUE THREAD

**Issue by i7366464** [XPoet/hexo-theme-keep#344]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.1.5` or later. （使用 Keep `4.1.5` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Other Information | 其它信息

在打包后，将生成的静态文件上传的服务器对应目录后，网站可以正常打开，但是菜单栏和文章均不能打开。
网站：https://www.openhots.com/

**Comment by i7366464** [comment]
keep配置文件，hexo配置文件，打包好的文件，已经通过邮箱发送给您。

**Comment by i7366464** [comment]
问题更新，文章可以打开了（上传过程中，文件名发生变化了），把文件压缩后，到服务器解压就能打开了，但是菜单栏依旧不能打开，看不到设置的内容。由于文章中有代码，在文章界面点击菜单栏会增加代码块，测试得到，文章可以打开，但是文章的中的代码块不能正常的折叠，点击后显示折叠了，也没有真正的折叠

**Comment by i7366464** [comment]
目前问题已经解决，那就是不要开cf的cdn，具体cdn的工作流程我不大懂，可能是此cdn还没缓存完我就开始访问网页了，但是这个可能性不大，毕竟静态文件一共也没多大，具体原因不详，总之，关闭了cf的cdn，就正常了。

**Comment by XPoet** [comment]
https://www.openhots.com 这个网站正常。
**你在本地运行正常，那 Keep 主题就是正常的，部署问题跟 Keep 主题本身没有直接关系。**

如果你需要在 https://xxx.com/xx 运行，对应的需要在 Hexo 的配置文件中设置：

```
url: https://xxx.com/xx
root: /xx
```
