### ISSUE TITLE
希望能提供文章加密功能

### ISSUE THREAD

**Issue by YinJiangyi** [XPoet/hexo-theme-keep#35]
采用hexo-blog-encrypt插件设置文章静态加密的时候，会影响部分正常功能。目前发现的，包括解密后toc无法显示，以及表格无法正常显示。

辛苦大大！

**Comment by XPoet** [comment]
👍 后续考虑加上

**Comment by XPoet** [comment]
作者发现 hexo-blog-encrypt 加密插件勉强能用，但使用后带来样式失效等问题不属于 Keep 主题造成的，要实现百分百兼容还需插件端配合。经评估，暂时不考虑兼容，后续由主题内置实现。
