### ISSUE TITLE
无法使用右上角的搜索功能

### ISSUE THREAD

**Issue by LuXugang** [XPoet/hexo-theme-keep#352]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.1.5` or later. （使用 Keep `4.1.5` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Expected behavior | 预期行为

右上角搜索功能无法使用

### Actual behavior | 实际行为

点击搜索有响应

### Steps to reproduce the behavior | 重现步骤

右上角搜索功能无法使用

### Node.js and NPM Information | Node.js 和 NPM 信息

```Text
右上角搜索功能无法使用
```

### Hexo Configuration | Hexo 配置

```YAML
右上角搜索功能无法使用
```

### Keep Configuration | Keep 配置

```YAML
右上角搜索功能无法使用
```

### Other Information | 其它信息

右上角搜索功能无法使用

**Comment by LuXugang** [comment]
升级到4.2.1后无法使用local_search

**Comment by XPoet** [comment]
经作者验证，local_search 功能正常可用。
请及时按要求提供有效信息，否则该 Issue 会被关闭。

**Comment by This-is-Y** [comment]
相同的问题，更新keep后出现的，
hexo -version
`hexo-cli: 4.3.2
os: win32 10.0.19045 undefined
node: 18.12.1
v8: 10.2.154.15-node.12
uv: 1.43.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.18.1
modules: 108
nghttp2: 1.47.0
napi: 8
llhttp: 6.0.10
openssl: 3.0.7+quic
cldr: 41.0
icu: 71.1
tz: 2022b
unicode: 14.0
ngtcp2: 0.8.1
nghttp3: 0.7.0
`

npm -version
8.19.2



blog\_config.yaml
……
search:
  path: search.json
  field: post
  content: true
  format: striptags
……


blog\themes\hexo-theme-keep\_config.yaml
……
local_search:
  enable: true   # Option values: true | false
  preload: false  # Preload the search data when the page loads. Option values: true | false
……

hexo server启动后，页面出现了搜索按钮，但是点击后无任何反应

浏览器中F12中有如下报错信息，不确定是否有用
![image](https://github.com/user-attachments/assets/9104a4c8-7896-4c30-816e-6338aa87a2ff)

**Comment by This-is-Y** [comment]
刚刚的图截少了一部分，
![image](https://github.com/user-attachments/assets/2d69d4ba-a4f3-4691-b400-e3588479e6c6)

**Comment by GaofengLu** [comment]
相同的问题，版本也是4.2.1

**Comment by XPoet** [comment]
请使用 v4.2.1 的各位，将 Hexo 博客源码（可删除 node_modules 和 文章）发送至作者邮箱 i@xpoet.cn，不然没法排查，作者反复验证，在 v4.2.1 下搜索功能可以正常使用，而且 v4.2.1 只优化了一点点样式，无其他改动。

**Comment by XPoet** [comment]
提出问题，请按 Issue 要求，提供完整的信息，不然无法排查

**Comment by LuXugang** [comment]
v4.1.3以及之前的版本是可以的  
v.4.1.4以及后续的版本都不行

**Comment by XPoet** [comment]
首先 local_search 功能一直是可以正常使用的，当你的环境下无法使用，请检查是否按文档教程来配置。
> [local_search 文档教程](https://keep-docs.xpoet.cn/basis/configuration-guide/local_search.html)

其次，提 Bug Issue 请务必按照 Issue 中的模板提供必要的信息，不然作者无法排查。

最后，未及时提供有效信息，该 Issue 会被关闭。

这两个网站都是 v4.2.1，local_search 都能正常使用。
1、https://xpoet.cn
2、https://keep.xpoet.cn

**Comment by XPoet** [comment]
local_search 在 v4.2.1 下无法使用的朋友们，请重新开一个 Bug Issue，按要求填写详细信息，不然没法排查和复现。该 Issue 先关闭。

**Comment by LuXugang** [comment]
升级到4.2.2搜索功能正常了 @XPoet
