### ISSUE TITLE
移动端表格排版不能横向滚动

### ISSUE THREAD

**Issue by justaLoli** [XPoet/hexo-theme-keep#361]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.1.5` or later. （使用 Keep `4.1.5` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Expected behavior | 预期行为

横向滚动或其他优化表格排版的方式
我曾经提出过issue #273 
现在这个问题在移动端仍然存在。面对稍长一点的表格，移动端的排版便会非常难看。
不论怎样，现在的排版显然不合适。

### Actual behavior | 实际行为

现在这个问题在移动端仍然存在。面对稍长一点的表格，移动端的排版便会非常难看。
不论怎样，现在的排版显然不合适。
给出两张截图，分别是桌面端和移动端对表格的显示效果
![CleanShot 2024-09-01 at 12 24 59](https://github.com/user-attachments/assets/fb4f9551-018c-4451-82
![CleanShot 2024-09-01 at 12 24 31](https://github.com/user-attachments/assets/c57b8f84-d768-4d1b-b439-5af9b7691078)
44-a83368e99e50)

### Steps to reproduce the behavior | 重现步骤

1. 新建博客
2. 写一个（甚至不需要）有很多很多列的表格
3. 部署，调整浏览器缩放 or 调整浏览器尺寸 or 使用响应式工具测试，将ui变换到手机模式，完成。

### Node.js and NPM Information | Node.js 和 NPM 信息

```Text
无用
v21.6.2
10.2.4
/hexo测试
├── hexo-abbrlink@2.2.1
├── hexo-asset-image@1.0.0
├── hexo-generator-archive@2.0.0
├── hexo-generator-category@2.0.0
├── hexo-generator-index@3.0.0
├── hexo-generator-tag@2.0.0
├── hexo-renderer-ejs@2.0.0
├── hexo-renderer-pandoc@0.4.0
├── hexo-renderer-stylus@3.0.0
├── hexo-server@3.0.0
├── hexo-theme-keep@4.2.2
├── hexo-theme-landscape@1.0.0
└── hexo@7.0.0
```

### Hexo Configuration | Hexo 配置

```YAML
出厂
```

### Keep Configuration | Keep 配置

```YAML
出厂
```

**Comment by XPoet** [comment]
下一版本优化

**Comment by XPoet** [comment]
移动端表格样式已优化，先已支持横向滚动，请使用 v4.2.3

<img width="316" alt="image" src="https://github.com/user-attachments/assets/242ed743-0012-4bd0-9853-3a05281ad641">
