### ISSUE TITLE
是否可以修改文章内反引号包裹文字的效果

### ISSUE THREAD

**Issue by miller-star** [XPoet/hexo-theme-keep#362]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.1.5` or later. （使用 Keep `4.1.5` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Other Information | 其它信息

文内反引号所包裹的文字效果如下图所示：
![XiaojunScreenshot2024-09-09 14 42 04](https://github.com/user-attachments/assets/25a1cfe9-af0c-4669-a36e-439cc3af6280)
配置文件中是否有可以更改这一效果的配置，比如改成github中`这种样式`

**Comment by XPoet** [comment]
你可以使用注入 CSS 来修改单行代码块的样式：
详情查看文档：https://keep-docs.xpoet.cn/basis/configuration-guide/inject.html#css

示例：
<img width="441" alt="image" src="https://github.com/user-attachments/assets/a73af186-541c-45bb-8f78-db4b86602a84">

<img width="815" alt="image" src="https://github.com/user-attachments/assets/62e24681-4c4d-488e-b22c-38fa7cf173cc">
