### ISSUE TITLE
移动端标题字数多导致渲染时比较拥挤

### ISSUE THREAD

**Issue by Catwb** [XPoet/hexo-theme-keep#365]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.2.3` or later. （使用 Keep `4.2.3` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Expected behavior | 预期行为

应该比较宽松一些

### Actual behavior | 实际行为

![Screenshot_2024-10-05-22-47-54-37_a252b927494330cdc2c8ba3b3f952e5e](https://github.com/user-attachments/assets/a7e31a81-832f-4d7e-82d8-d3d32470f023)

### Steps to reproduce the behavior | 重现步骤

正常加载

### Node.js and NPM Information | Node.js 和 NPM 信息

```Text
none
```

### Hexo Configuration | Hexo 配置

```YAML
none
```

### Keep Configuration | Keep 配置

```YAML
none
```

### Other Information | 其它信息

移动端，via浏览器，kiwi浏览器

**Comment by XPoet** [comment]
改问题已优化，请使用 `v4.2.4`
