### ISSUE TITLE
【移动端】twikoo表情页过大使与footer文字重合

### ISSUE THREAD

**Issue by Catwb** [XPoet/hexo-theme-keep#366]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.2.3` or later. （使用 Keep `4.2.3` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [x] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Expected behavior | 预期行为

表情块应当遮挡footer文字

### Actual behavior | 实际行为

![Screenshot_2024-10-06-20-46-47-71_a252b927494330cdc2c8ba3b3f952e5e](https://github.com/user-attachments/assets/05bb0905-ba00-4ee8-a04c-cfe2476436b5)

而且无法点击与footer文字重合的地方（应该说，优先点击到的是footer中的超链接，如hexo，keep）

### Steps to reproduce the behavior | 重现步骤

none

### Node.js and NPM Information | Node.js 和 NPM 信息

```Text
none
```

### Hexo Configuration | Hexo 配置

```YAML
none
```

### Keep Configuration | Keep 配置

```YAML
none
```

### Other Information | 其它信息

移动端

**Comment by XPoet** [comment]
由于作者没使用 twikoo 评论插件，可否提供下你 twikoo 的 env_id 和 version，仅供作者验证问题和修复

**Comment by Catwb** [comment]
env_id: https://test.qiyao.cloudns.ch/.netlify/functions/twikoo
version: 1.6.39

**Comment by Catwb** [comment]
今晚发现电脑端也会出现这样的问题🧐
Edge 127.0.0.0
Windows 11
