### ISSUE TITLE
关于主题更新

### ISSUE THREAD

**Issue by cemonliu** [XPoet/hexo-theme-keep#37]
如果更新了主题，是否设置的yml文件要重新设置一遍？ 有没有其他方法？

**Comment by XPoet** [comment]
1. 在你 Hexo 项目的 `source` 文件夹里增加 `_data` 文件夹。

2. 把主题配置文件 `_config.yml` 复制到 `_data` 文件夹，重命名为 `keep.yml`。

3. 以后升级主题了，只需修改 `_data` 文件夹下的 `keep.yml`。注意：`keep.yml` 的 `version` 值需跟 `_config.yml` 的 `version` 值保持一致。

![image](https://user-images.githubusercontent.com/24516169/103983686-ac3a3a80-51c0-11eb-9d2f-6e6d4889e911.png)

**Comment by XPoet** [comment]
![Uploading image.png…]()

**Comment by XPoet** [comment]
![image](https://user-images.githubusercontent.com/24516169/103983809-e4417d80-51c0-11eb-9946-a8246a2fa71f.png)

**Comment by cemonliu** [comment]
感谢 !
