### ISSUE TITLE
置顶块过长

### ISSUE THREAD

**Issue by Catwb** [XPoet/hexo-theme-keep#370]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.2.3` or later. （使用 Keep `4.2.3` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Expected behavior | 预期行为

none

### Actual behavior | 实际行为

<img width="126" alt="屏幕截图 2024-10-27 131429" src="https://github.com/user-attachments/assets/36398cec-8e78-430d-a9de-8ad850d573fc">

后来发现并没有置顶上

### Steps to reproduce the behavior | 重现步骤

sticky: 114514

### Node.js and NPM Information | Node.js 和 NPM 信息

```Text
none
```

### Hexo Configuration | Hexo 配置

```YAML
none
```

### Keep Configuration | Keep 配置

```YAML
none
```

### Other Information | 其它信息

Windows 11
Edge 127.0.0.0

**Comment by XPoet** [comment]
发一下你出现这种异常现象的链接

**Comment by Catwb** [comment]
https://blog.qiyao.us.kg/

**Comment by XPoet** [comment]
你这问题跟 Keep 主题无关，你使用的第三方 fclite 样式影响到了 Keep 主题样式

**Comment by XPoet** [comment]
作者在主题内部做了优化，防止被第三方样式侵入影响，请使用最新版本 `v4.2.4`
