### ISSUE TITLE
是否可以将代码块默认为折叠状态？

### ISSUE THREAD

**Issue by FlyOverAsia** [XPoet/hexo-theme-keep#371]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.2.3` or later. （使用 Keep `4.2.3` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Feature Request | 功能需求

您好！Keep主题中的代码块收缩功能很棒，但是在移动端略显紧凑的文章中，收缩过的代码块似乎还是显得占用空间了。
所以我可能需要使代码块默认为折叠状态，由使用者自行选择是否展开代码块。
我注意到折叠和展开代码块时“code-tools-box”和“highlight plaintext”两项活跃，但是并不清楚如何修改，希望和感谢开发者的帮助！

**Comment by XPoet** [comment]
暂不支持。
