### ISSUE TITLE
希望inject功能支持直接在head/footer inject代码

### ISSUE THREAD

**Issue by tyadan** [XPoet/hexo-theme-keep#373]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.2.3` or later. （使用 Keep `4.2.3` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Feature Request | 功能需求

有一些代码需要特殊的加载方式，默认inject方式的话，只能支持常规方式inject css/js，建议可以在head/footer直接inject代码，这样自定义化程度高，比较方便，参考
<img width="793" alt="image" src="https://github.com/user-attachments/assets/4a5db8d1-71e8-499a-9f65-dcea301c709a">

**Comment by tyadan** [comment]
更新，hexo官方支持https://hexo.io/zh-cn/api/injector Inject，通过在根目录下新建scripts文件夹后，手动注入js即可，似乎无需主题支持，默认就可以

**Comment by XPoet** [comment]
对的，使用 hexo 框架自带功能即可实现，无需主题额外开发
