### ISSUE TITLE
Post tool 无法点击

### ISSUE THREAD

**Issue by Catwb** [XPoet/hexo-theme-keep#377]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.2.4` or later. （使用 Keep `4.2.4` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Expected behavior | 预期行为

可以进行互动

### Actual behavior | 实际行为

- https://blog.qiyao.us.kg/

无法点击

### Steps to reproduce the behavior | 重现步骤

none

### Node.js and NPM Information | Node.js 和 NPM 信息

```Text
none
```

### Hexo Configuration | Hexo 配置

```YAML
none
```

### Keep Configuration | Keep 配置

```YAML
none
```

### Other Information | 其它信息

在发现这个问题的时候，我记得提交有个更改是`z-index`，于是我打开了开发人员选项，在post-tools right-toc和post-tools-list border-box部分，设置`z-index`为一个大数便能够使用

**Comment by XPoet** [comment]
收到反馈，紧急修复

**Comment by XPoet** [comment]
该问题已修复，请使用 `v4.2.5`
