### ISSUE TITLE
3.1.3开启评论后，如果没有评论内容多一个sofa字样

### ISSUE THREAD

**Issue by cemonliu** [XPoet/hexo-theme-keep#38]
![image](https://user-images.githubusercontent.com/42933407/103976994-2ebbfd80-51b3-11eb-87cd-502afecc261b.png)

**Comment by XPoet** [comment]
你 hexo 的配置文件 `language` 不能这样设，只能设置一种！！

![image](https://user-images.githubusercontent.com/24516169/103982698-eefb1300-51be-11eb-894d-49dc1dc4f6ea.png)

**Comment by XPoet** [comment]
改成 `language: zh-CN` 或 `language: en`

Valine 评论系统的语言根据你的 hexo 配置来的

**Comment by cemonliu** [comment]
果然，学习了。改完之后变成：来发评论吧~
