### ISSUE TITLE
编译后校验./css/layout/page.css中有异常keep-tablet()/keep-mobile()

### ISSUE THREAD

**Issue by yanzhenjie** [XPoet/hexo-theme-keep#382]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.2.5` or later. （使用 Keep `4.2.5` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Other Information | 其它信息

<i>20241219 - update: </i>
XPoet您好，项目风格和代码质量都很棒，个人很喜欢，点个赞。遇到点小问题来请教一下，相关产品文档已烂熟于心，个人非前端专业，所以请教下。我自己的Blog和xpoet.github.io下的编译产物中，./css/layout/page.css中都有异常keep-tablet()/keep-mobile()，网站可以正常跑，我理解这不是我项目的问题。请教下这是编译的问题还是什么原因？是否会有任何不利影响？感谢！！！

**Comment by XPoet** [comment]
没有不利影响，正常编译产物。
