### ISSUE TITLE
Font Awesome 网站打不开了。

### ISSUE THREAD

**Issue by MemoryCollection** [XPoet/hexo-theme-keep#383]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.2.5` or later. （使用 Keep `4.2.5` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Expected behavior | 预期行为

Font Awesome 网站打不开了。

### Actual behavior | 实际行为

- Links to demo site with this issue （链接到这个 IssuFont Awesome 网站打不开了。e 的演示网站）
- Links to source code of the blog with this issue （链接到这个 Issue 的博客源代码）
- Screenshots（屏幕截图）
Font Awesome 网站打不开了。

### Steps to reproduce the behavior | 重现步骤

1. First step ...   （第一步 ...）
2. Second step ...  （第二步 ...）
3. Third step ...   （第三步 ...）
Font Awesome 网站打不开了。

### Node.js and NPM Information | Node.js 和 NPM 信息

```Text
Font Awesome 网站打不开了。
```

### Hexo Configuration | Hexo 配置

```YAML
Font Awesome 网站打不开了。
```

### Keep Configuration | Keep 配置

```YAML
Font Awesome 网站打不开了。
```

### Other Information | 其它信息

Font Awesome 网站打不开了。

**Comment by XPoet** [comment]
1、https://fontawesome.com 网站可以正常访问，如不能，必然是你网络问题。
2、https://fontawesome.com 就算无法访问，也不属于 Keep 范畴的 Bug，请谨慎提 Issue。
