### ISSUE TITLE
关于主题的版本号

### ISSUE THREAD

**Issue by liuyib** [XPoet/hexo-theme-keep#39]
举例：

![image](https://user-images.githubusercontent.com/38221479/104080574-da248b00-5263-11eb-9ea3-502f77a7816a.png)

版本号不符合规范，其中，都添加了新的 feature，直接改动次版本号就好了，你直接 `v3.1.1 -> v3.1.2` 只改动了修订号，很容易误导用户，某些情况下甚至会引起 Hexo 启动报错。

https://semver.org/lang/zh-CN/

![image](https://user-images.githubusercontent.com/38221479/104080592-fe806780-5263-11eb-9fa5-335b6d9cffeb.png)

---

可能你觉着就加了一个小功能而已，没必要改动次版本号，这是不对的。举个例子：假如你刚发布了 `v2.4.0`，然后新的 commit 中，提交了一个 `feat:`，如果想再发布新版本，就得直接 `v2.5.0`。

---

另外建议你，涉及改动配置（`_config.yml`）的 commit，你心里要清楚，改动配置相当于 ​Breaking Changes，如果改动配置就得发布新的主版本号，哪怕只新提交了一个 commit。

众所周知，发布新的主版本号不是小事情，因此需要谨慎对待。所以建议把涉及 `配置改动的`、`用法和之前完全不一样的（哪怕配置完全相同）` 都放入计划中，等积攒多了再去实现，然后发布一个大的主版本号。

---

我是 [hexo-theme-stun](https://github.com/liuyib/hexo-theme-stun) 主题的作者，以上是我的愚见（都是坑过来的，，，），也是我诚心的建议，如有不妥，恳请斧正，希望多多交流。

**Comment by XPoet** [comment]
@liuyib 多谢指正，学习了，多交流 🤝
