### ISSUE TITLE
希望能加一个启用toc但是默认折叠的选项

### ISSUE THREAD

**Issue by miranquil** [XPoet/hexo-theme-keep#40]
RT，感觉目前的目录由于移动了整个页面布局，在子标题没有那么多的文章就显得很突兀，如果可以默认折叠左边栏，需要时候再点开就好了。

**Comment by XPoet** [comment]
很好的建议，下个版本加上

**Comment by XPoet** [comment]
v3.3.2 已发布，该版本增加了样式状态（侧边栏折叠、字体大小、页面宽度设置）的持久化存储，比如：点击隐藏了侧边的 TOC 目录，下次刷新页面时，将读取之前的状态，即不显示。

请使用最新版本

**Comment by miranquil** [comment]
好耶
