### ISSUE TITLE
NPM 如何升级主题？

### ISSUE THREAD

**Issue by markruan** [XPoet/hexo-theme-keep#43]
如题，npm 只会更新node_modules里的文件内容，要复制到themes文件夹下吗？

**Comment by XPoet** [comment]
- 如果你在使用 Hexo 5.0 或更高版本，最简单的安装方式是通过 npm：

  ```sh
  $ cd hexo-site
  $ npm install hexo-theme-keep
  ```

- 通过 npm 更新到最新版本：

  ```sh
  $ cd hexo-site
  $ npm update hexo-theme-keep
  ```

**Comment by XPoet** [comment]
不用复制到 themes 文件夹下

**Comment by markruan** [comment]
> 不用复制到 themes 文件夹下。该方式下的主题配置文件最佳存储参考 #37

ok ,这个没写在主题官网文档里，现在明白了

**Comment by XPoet** [comment]
最近实在是太忙了，过阵子整理份详细的文档出来

**Comment by XPoet** [comment]
Keep 主题官方文档：https://keep-docs.xpoet.cn/

[Keep 平滑升级教程](https://keep-docs.xpoet.cn/usage-tutorial/advanced.html#%E5%B9%B3%E6%BB%91%E5%8D%87%E7%BA%A7)
