### ISSUE TITLE
在晚上，单行代码段及长代码的背景色反色

### ISSUE THREAD

**Issue by miranquil** [XPoet/hexo-theme-keep#45]
暗色模式下的 三连反引号包含的长代码片段背景仍然是纯白色，在暗色模式下非常扎眼。
另外单反引号扩起来的单行代码同样有这个问题。

**Comment by XPoet** [comment]
感谢反馈，麻烦截个图，并把 Markdown 代码也发一下，以便作者快速排查问题

**Comment by miranquil** [comment]
Emmm似乎是我本地缓存的问题，清空重载后复现失败了_(:з」∠)_自闭了

**Comment by miranquil** [comment]
重开问题，RT，这个 bug 只有在晚上才会触发（怀疑是系统激活深色模式以后）。
操作系统 macOS Big Sur 11.1，目前无论是 Safari 浏览器 还是 Firefox 进入我自己或者作者的站，代码段的背景颜色都是与当前主题色相反（夜间模式白色白昼模式黑色），而在白天表现正常。

**Comment by miranquil** [comment]
我更改 System Preference 做了测试，如果锁定 Appearance 是 Light 的话正常，切换至 Dark 主题整体颜色会随即改变至深色但代码背景未受影响。猜测是这里少了一个自动切换的触发导致。

另外，以 Dark Mode 进入站点会发现右下角按钮里的太阳/月亮图标还是太阳（白昼模式），点两下才会恢复正常的匹配。

**Comment by XPoet** [comment]
我也发现这个问题了，正准备优化，回头看看测试一下你 PR 的代码
