### ISSUE TITLE
空页面Title问题（好吧其实还是link）

### ISSUE THREAD

**Issue by miranquil** [XPoet/hexo-theme-keep#48]
在之前的issue有提到一个[link页面出现“link”标题](https://github.com/XPoet/hexo-theme-keep/issues/28#issuecomment-761580823)的问题，但未深究。

我看了Repo主的博客没有出现这个问题，后查代码得知问题出在`themes/keep/layout/_partial/empty-page.ejs`下：

```ejs
        <div class="empty-page-content markdown-body">
            <% if (page.content) { %>
                <%- page.content %>
            <% } else { %>
                <h1><%- page.title %></h1>
            <% } %>
        </div>
```

这一段会使得*任何类似友链的空页面*在**内容为空**时出现一个`<h1><%- page.title %></h1>`。而在主题的逻辑里，page.title作为hexo判断页面分类的依据不可缺少。

而恰好Repo主的博客，友链页面有一段介绍文字（即`page.content`结果为真），而我的却刚好没有😂。

我个人有两个解决方案：一是简单的将上文代码中`else`改写为额外的`else if`并判断`page.title`是否为`link(s)`。另一种是将整个主题的页面分类依据从`title`改为`type`，不过这样需要更新所有旧的md。

**Comment by XPoet** [comment]
👍 细节问题，你考虑的很周全，合并了

**Comment by XPoet** [comment]
采用 page.title 作为页面判断逻辑是因为在创建页面时会自动加上 title 属性。
我再完善下该部分判断逻辑，添加可选的 type 属性

**Comment by miranquil** [comment]
> 采用 page.title 作为页面判断逻辑是因为在创建页面时会自动加上 title 属性。
> 我再完善下该部分判断逻辑，添加可选的 type 属性

倒是觉得这样会限制住用户具体的Title内容，比如有些人喜欢用一些奇怪的Title，目前的逻辑不存在title与content共存倒也一定程度上规避了这个问题，不过终究还是限制了灵活度。我下午自己开了个分支用type发现其实要改的东西还蛮少的，title和content都可以选择留空也算是客制化空间更大吧。
