### ISSUE TITLE
gittalk 评论插件样式

### ISSUE THREAD

**Issue by Varsion** [XPoet/hexo-theme-keep#51]
今天开了评论插件之后 样式炸了 没有改动主题代码

**Comment by Varsion** [comment]
这个是页面截图
![image-page](https://img.varsion.cn/pagess.png)

**Comment by XPoet** [comment]
gitalk 评论插件的样式没错乱。
这个网站  https://keep.xpoet.cn/ 就使用了 gitalk 。
你清空浏览器缓存再试试看

**Comment by Varsion** [comment]
好的 我想我已经解决了这个问题 thx
