### ISSUE TITLE
希望文章页面的作者昵称后面 “Lv~”可换自定义设置

### ISSUE THREAD

**Issue by o-oil** [XPoet/hexo-theme-keep#55]
主题真的非常流畅，简洁漂亮，爱了
希望作者增加一个功能，在文章页作者昵称后面的 “Lv~” 可换自定义设置
![image](https://user-images.githubusercontent.com/70268614/106082010-e5792100-6154-11eb-88f4-9941e385b4c8.png)

**Comment by XPoet** [comment]
该功能已在 `v3.4.0` 实现，请使用最新版本
