### ISSUE TITLE
关于标签

### ISSUE THREAD

**Issue by aiiibolo** [XPoet/hexo-theme-keep#57]
如果在写文章的时候添加了标签，文章在博客里就无法显示。
猜想的原因是没有在source里面添加tag的index？
请问如果是我猜想的原因的话tag的index页该是什么格式呢

第二个问题就是我文章里的图片无法在博客中显示，图片的是放在图床中的，请问有可能是什么原因导致的呢？

**Comment by XPoet** [comment]
@aiiibolo 
问题一：Keep 主题是支持显示标签的，请提供一下你写的文章 md 文件的 tags 属性。
格式参考：
```
---
title: Keep 主题使用指南
date: 2020-04-07 21:55:14
tags: [Hexo, Keep]
categories: [Keep]
sticky: 999
---
```

**Comment by XPoet** [comment]
问题二：请确保你的图片外链能正常访问，麻烦提供一下你写的 md 格式，我看看正不正确？

**Comment by aiiibolo** [comment]
关于问题一的回复：是我格式写的不对。稍后验证一下，
关于问题二的回复：格式没有错，我在本地的md编辑工具里面，都可以显示，我有两篇文章，一篇可以显示一篇不能，方便留哥邮箱吗，我可以把两篇文章发给你

**Comment by XPoet** [comment]
你把图片那部分 md 发出来，直接发这里，可能是路径问题

**Comment by aiiibolo** [comment]
格式如下：![](https://ftp.bmp.ovh/imgs/2021/01/ee47704cc8610a1b.png)

**Comment by XPoet** [comment]
@aiiibolo 
没内容，发邮件吧 i@xpoet.cn

**Comment by aiiibolo** [comment]
我这边看我的回复出来的是一张图片，然后我又去重新检查了一下，应该是图床的问题，换了图床以后解决了，不是主题的问题，谢谢
