### ISSUE TITLE
访问人数和访问量相同

### ISSUE THREAD

**Issue by Lovzi** [XPoet/hexo-theme-keep#58]

**Comment by XPoet** [comment]
清空浏览器缓存再看看

**Comment by Lovzi** [comment]
> 清空浏览器缓存再看看

你好，还是一样的
![Uploading image.png…]()

**Comment by XPoet** [comment]
@Lovzi 
你的截图没上传成功，无法查看，再发一次。

并且提供下你的博客网址

**Comment by Lovzi** [comment]
您好， 截图如下
![截图](https://user-images.githubusercontent.com/42086982/106994205-4b9a1f80-67b7-11eb-867a-092b4d20313d.png)
链接如下[博客](http://lovzi.cn/)

**Comment by XPoet** [comment]
Keep 主题使用的是不蒜子计数，在作者博客下，发现计数功能正常。
可能是因为你使用 http 协议 ，非 https。建议你的网站使用 https 。
![image](https://user-images.githubusercontent.com/24516169/106996833-a7b37280-67bc-11eb-988e-ee1e50d40171.png)

**Comment by Lovzi** [comment]
> Keep 主题使用的是不蒜子计数，在作者博客下，发现计数功能正常。
> 可能是因为你使用 http 协议 ，非 https。建议你的网站使用 https 。
> ![image](https://user-images.githubusercontent.com/24516169/106996833-a7b37280-67bc-11eb-988e-ee1e50d40171.png)

感谢大佬，确实就是这个问题，我使用https，现在计数已经正常。
