### ISSUE TITLE
主题设置后，网站界面一直有个圈是什么没加载成功？

### ISSUE THREAD

**Issue by cemonliu** [XPoet/hexo-theme-keep#59]
网站地址如下，
https://blog.gooday.press

![图片](https://cdn.jsdelivr.net/gh/cemonliu/blogpic@main/20210206092321.png)

**Comment by cemonliu** [comment]
过了一会，现在又复现不了了。

**Comment by XPoet** [comment]
@cemonliu  
这是因为你升级了 Keep 主题浏览器缓存引起的，下次遇到这种情况，清空下浏览器缓存即可。
