### ISSUE TITLE
Mermaid支持

### ISSUE THREAD

**Issue by dawnchan030920** [XPoet/hexo-theme-keep#60]
如题，希望能够增加对Mermaid的主题支持。我尝试了`hexo-filter-mermaid-diagrams`，并没有奏效。

**Comment by XPoet** [comment]
@dawnchan030920 
Keep 目前不支持 Mermaid，下一版本可能会加上，届时会告知。

**Comment by XPoet** [comment]
原理上该功能跟任何主题无关，提升 Hexo 版本试试
