### ISSUE TITLE
顶部菜单渐变样式支持

### ISSUE THREAD

**Issue by xcbyao** [XPoet/hexo-theme-keep#62]
希望可以优化下 first_screen 顶部菜单栏的样式，类似于 butterfly or Matery  改善成透明色，下拉渐变的样式，让首页更精美；
而且背景图替换后，强制放大效果不太好，希望能配合渐变，支持原图替换成全屏页面。

**Comment by XPoet** [comment]
挺好的建议，有空我改样式看看

**Comment by EvanNotFound** [comment]
我改了主题导航栏，类似 Butterfly 主题样式，你可以试试看：[https://github.com/EvanNotFound/hexo-theme-redefine](https://github.com/EvanNotFound/hexo-theme-redefine)
