### ISSUE TITLE
¶创建磁盘分区 生成的标题前面多了一个符号

### ISSUE THREAD

**Issue by rainbow7** [XPoet/hexo-theme-keep#64]
除了H1级别，其他级别都会有这个符号是什么原因？

**Comment by XPoet** [comment]
截个图我看看

**Comment by rainbow7** [comment]
![image](https://user-images.githubusercontent.com/5925440/108713013-97d4b600-7552-11eb-8af4-a61eea526825.png)
![image](https://user-images.githubusercontent.com/5925440/108713025-9acfa680-7552-11eb-983e-a803f504cc00.png)
![image](https://user-images.githubusercontent.com/5925440/108713031-9c996a00-7552-11eb-8d51-b8998a941fb1.png)

生成的html有一些不同，不知道是什么原因。

**Comment by rainbow7** [comment]
![image](https://user-images.githubusercontent.com/5925440/108713250-eaae6d80-7552-11eb-99e4-0717a667145e.png)
我使用h1，h3生成出的html是这样的。使用h1时，与你的博客生成的html也是不同的。是markdown编辑器的问题吗？标题是使用#号。

# H1
### H3

**Comment by XPoet** [comment]
你写的这段文字的 md 格式发一下

**Comment by rainbow7** [comment]
![image](https://user-images.githubusercontent.com/5925440/108799249-c9896380-75ca-11eb-889a-bd3deab33da7.png)

**Comment by rainbow7** [comment]
![image](https://user-images.githubusercontent.com/5925440/108801180-fbe98f80-75cf-11eb-99b4-dd128e4b8d04.png)
实在抱歉，找到问题了。是我自己没搞清楚这些配置。很喜欢这个主题。从立意、美观、功能上都很喜欢。感谢，加油。

**Comment by XPoet** [comment]
谢谢支持 Thanks♪(･ω･)ﾉ
