### ISSUE TITLE
友链样式问题

### ISSUE THREAD

**Issue by lxh20061128** [XPoet/hexo-theme-keep#69]
https://keep-docs.xpoet.cn/usage-tutorial/advanced.html#友链样式
每一步都是跟着教程走，可是最后还是没变化

**Comment by XPoet** [comment]
检查下 links 页面有没有创建？

可使用如下命令自动创建
```
hexo new page links
```

**Comment by XPoet** [comment]
截一张你的 hexo 项目图我看看，类似下图，要能够看到项目结构和 links.yml
![](https://cdn.jsdelivr.net/gh/XPoet/image-hosting@master/keep-docs/image.411k8ek37x40.png)

**Comment by lxh20061128** [comment]
这样可以吗
![https://img.imgdb.cn/item/60424524360785be542a156c.png]()
![https://img.imgdb.cn/item/60424524360785be542a1573.png]()
![https://img.imgdb.cn/item/60424524360785be542a157a.png]()

**Comment by lxh20061128** [comment]
请原谅，图片不会上传，复制链接打开吧

**Comment by lxh20061128** [comment]
![](https://img.imgdb.cn/item/60424524360785be542a156c.png)
![](https://img.imgdb.cn/item/60424524360785be542a1573.png)
![](https://img.imgdb.cn/item/60424524360785be542a157a.png)

**Comment by lxh20061128** [comment]
![](https://img.imgdb.cn/item/60424524360785be542a156c.png)

**Comment by lxh20061128** [comment]
![](https://img.imgdb.cn/item/60424524360785be542a1573.png)

**Comment by lxh20061128** [comment]
![](https://img.imgdb.cn/item/60424524360785be542a157a.png)

**Comment by XPoet** [comment]
你的 hexo 项目结构没啥问题。

检查一下你的 Keep 主题配置文件 `_config.yml` 的 `menu` 配置项里面有没有开启 `links` 
```yaml
menu:
  Home: /
  Links: /links
  # ......
```

**Comment by XPoet** [comment]
你的 `/hexo/source/links/index.md` 文件打开也截图我看一下

**Comment by XPoet** [comment]
![image](https://user-images.githubusercontent.com/24516169/110191842-9d40d300-7e65-11eb-805b-cbf16d2164b2.png)

这个文件先删除看看，暂不清楚是不是该配置文件冲突了

**Comment by lxh20061128** [comment]
1. links打开了 ![](https://img.imgdb.cn/item/60430a17360785be547dac57.png)
2. links/index.md ![](https://img.imgdb.cn/item/60430a64360785be547dd3a6.png)
3. -config.landscape.yml我也不知道是什么，文件是空的，删除以后没有用

**Comment by lxh20061128** [comment]
我真的是一步一步按着教程走的啊，是不是教程有点问题？

**Comment by XPoet** [comment]
links/index.md  文件里面的属性 title 不要修改！！！
请改回：title: links 
问题就出在这里

**Comment by lxh20061128** [comment]
已经解决，谢谢啦，links/index.md是因为前面用别的主题，title的文字会显示在上面，所以就给改了
