### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by wasd-debug** [XPoet/hexo-theme-keep#7]
主题十分简约漂亮，十分喜欢，希望尽快支持数学公式渲染。
菜单中标签多了之后的排版问题。
一些其他的丰富功能，比如打赏，分享。
建议增加有限图标。
还有分类目录中最多显示十篇文章的问题

**Comment by wasd-debug** [comment]
期待更新

**Comment by wasd-debug** [comment]
建议增加标签菜单

**Comment by wasd-debug** [comment]
或在首页中文章下面显示标签

**Comment by XPoet** [comment]
很不错的建议，我会尽快更新下一版本。

**Comment by wasd-debug** [comment]
发现图片加载不了，这是我自己的问题嘛？？？我已经上传到云了呀。写的是外链

**Comment by XPoet** [comment]
@wasd-debug 
检查一下你的图片外链是否能正常显示 或 你写的 Markdown 语法是否正确
[Markdown语法参考](https://xpoet.cn/2017/10/%E5%BF%AB%E9%80%9F%E6%8E%8C%E6%8F%A1Markdown%E5%9F%BA%E7%A1%80%E8%AF%AD%E6%B3%95/)

**Comment by stevenjoezhang** [comment]
数学公式渲染可以使用插件： https://github.com/next-theme/hexo-filter-mathjax

**Comment by Akie-hub** [comment]
建议添加一份配置示例

**Comment by zhang-hao-Github** [comment]
是指对 对接支付宝当面付 的一个流程上面的一个配置示例是么 马上就进行一个简单配置的说明 感谢小伙伴的建议 thank you ！



在 2020-10-10 20:55:26，"Akie-hub" <notifications@github.com> 写道：

建议添加一份配置示例

**Comment by Akie-hub** [comment]
我没讲清楚，我的意思是添加一个示例的[博客](https://xpoet.cn/)的_config.yml文件，这样像我这种小白只要对着改就行。
配置说明中好像没有对图片中的XPoet Blog部分进行说明，找了好久才知道是hexo配置文件中的site title。
![img](https://i.loli.net/2020/10/10/zKLhBMWYgrx86Ap.png)
希望首页左侧边栏上方能显示头像。
最后感谢各位贡献者，这是非常不错的主题，期待更新。

**Comment by XPoet** [comment]
@Akie-hub 很好的建议👍，抽空我写一份详细的配置项文档说明。

**Comment by XPoet** [comment]
关于 ILS 主题配置文件的详细图文教程，大家可参考这篇文章：
https://ils.xpoet.cn/2020/10/ILS-主题配置文件图文教程/

**Comment by XPoet** [comment]
原 Hexo 主题 ILS 已改名 Keep，主题配置文件图文教程请查看  [Keep 主题配置指南](https://keep.xpoet.cn/2020/11/Keep-%E4%B8%BB%E9%A2%98%E9%85%8D%E7%BD%AE%E6%8C%87%E5%8D%97/)

**Comment by hang1007** [comment]
您好！我发现在点击目录跳转后，最上方菜单栏会消失，这是bug嘛？如果不是希望您能为我解惑，我该如何保持菜单一直存在。
