### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by laopanmemz** [XPoet/hexo-theme-keep#70]
1.能不能加一个网页在左上角能放LOGO的功能
2.能不能加一个设置网页透明度的功能，想在后面加特效

**Comment by XPoet** [comment]
- 第一个建议：后续版本会加上该项配置。
- 第二个建议：你说的网页透明度是指整体的网页的透明，还是局部模块的透明？

**Comment by lxh20061128** [comment]
大佬我是这样想的，那个菜单栏能不能搞成透明的？或者半透明，首屏换图片根据特别别扭不同意
![Uploading QQ截图20210306195310.png…]()

**Comment by lxh20061128** [comment]
文章以外这个版块能不能透明掉，可以设置背景的那种，全是黑的或白的感觉也不好看
![](https://img.imgdb.cn/item/60436e77360785be54b388a1.png)

**Comment by lxh20061128** [comment]
![](https://img.imgdb.cn/item/60436e77360785be54b388a1.png)

**Comment by XPoet** [comment]
@lxh20061128 
建议已采纳，后续主题开发中会考虑这些问题

**Comment by HuOneNumber** [comment]
关于分类页面的建议，希望结构可以清晰一点。比如，做成可伸展的目录结构，或者对次一级的分类进一步的向右缩进，也可以对不同等级的分类进行字体大小等样式的区分；其次就是最低级的分类右边不显示文章数量好一点，显示的都是【1】

**Comment by XPoet** [comment]
@HuOneNumber 
挺好的建议，后续版本会优化你提到的这些问题

**Comment by XPoet** [comment]
keep `v3.4.8` 已基本满足该 issue 下的需求，大家请使用最新版本。
