### ISSUE TITLE
引用栏与列表显示优化问题

### ISSUE THREAD

**Issue by xcbyao** [XPoet/hexo-theme-keep#73]
![image](https://user-images.githubusercontent.com/40726291/110716920-16b03b00-8243-11eb-8c7b-847313ea24c2.png)

如图，列表序号和引用侧边栏重合，期待优化 😀

**Comment by XPoet** [comment]
多谢反馈，会尽快优化

**Comment by XPoet** [comment]
刚发布的 `v3.4.2` 已修复该问题 😺，该 Issue 关闭

**Comment by XPoet** [comment]
请更新至 `v3.4.2`
