### ISSUE TITLE
设置开启评论后重新部署页面空白？

### ISSUE THREAD

**Issue by Catherinezzzz** [XPoet/hexo-theme-keep#74]
尝试了valine和twikoo，只要填写了id之类的属性，重新部署后页面上就什么都没有一片空白，删掉就没有问题了。。按教程来的TAT

**Comment by XPoet** [comment]
1、开启评论后，你在本地运行时，评论系统有没有出来？
2、请提供你下你的 Keep 主题配置文件、Hexo 项目源文件（未编译前的）、空白页面的网址

**Comment by Catherinezzzz** [comment]
> 1、开启评论后，你在本地运行时，评论系统有没有出来？
> 2、请提供你下你的 Keep 主题配置文件、Hexo 项目源文件（未编译前的）、空白页面的网址

抱歉，是我的问题，我忽视了YAML语法冒号后面需要有一个空格...问题出在这里
