### ISSUE TITLE
categories 页面命名为 word1 Word2 第二个词首字母大写则部署后 404

### ISSUE THREAD

**Issue by xcbyao** [XPoet/hexo-theme-keep#79]
很玄学，categories 里命名为 word1 Word2 word3... 这类名字，测试了下只要第二个 Word 首字母大写，本地可以打开页面，但是部署到 GitHub Pages 就 404，
比如这种的 https://xcbyao.github.io/categories/Relive-Youth/ 部署后404
改成 https://xcbyao.github.io/categories/Relive-youth/ 部署后就正常

**Comment by XPoet** [comment]
这跟 Keep 主题无关了，GitHub Pages 的锅... 以后分类时，避免这种情况即可，你不提出来，我也不清楚 😵

**Comment by xcbyao** [comment]
哦了解啦，谢谢解答😀
