### ISSUE TITLE
评论功能配置

### ISSUE THREAD

**Issue by 987603843** [XPoet/hexo-theme-keep#80]
你好 我想请问我配置了评论功能 使用的是valine 但是我在页面评论的时候提交之后好像没有成功，
![image](https://user-images.githubusercontent.com/49261839/113233810-9aa19400-92d2-11eb-8882-f69ac46b7c4d.png)
请问这是什么原因呢

**Comment by XPoet** [comment]
评论提交失败，就是 Valine 评论插件配置有问题
提供下你的博客地址

**Comment by 987603843** [comment]
你好 博客地址是lzmiracle.com



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 指间的诗意 ***@***.***&gt;
发送时间: 2021年4月1日 11:38
收件人: XPoet/hexo-theme-keep ***@***.***&gt;
抄送: 987603843 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[XPoet/hexo-theme-keep] 评论功能配置 (#80)





 
评论提交失败，就是 Valine 评论插件配置有问题
 提供下你的博客地址

**Comment by XPoet** [comment]
你网站的评论插件能正常使用
你清除浏览器缓存再试试看
![image](https://user-images.githubusercontent.com/24516169/113242361-62ef1800-92e3-11eb-9f1a-15416f22ce7a.png)

**Comment by 987603843** [comment]
好的 我去看看 谢谢了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 指间的诗意 ***@***.***&gt;
发送时间: 2021年4月1日 12:12
收件人: XPoet/hexo-theme-keep ***@***.***&gt;
抄送: 987603843 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[XPoet/hexo-theme-keep] 评论功能配置 (#80)





 
你网站的评论插件能正常使用
 你清除浏览器缓存再试试看

**Comment by 987603843** [comment]
好的 谢谢了 已经解决 应该是网络问题连了局域网被限制了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 指间的诗意 ***@***.***&gt;
发送时间: 2021年4月1日 12:12
收件人: XPoet/hexo-theme-keep ***@***.***&gt;
抄送: 987603843 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[XPoet/hexo-theme-keep] 评论功能配置 (#80)





 
你网站的评论插件能正常使用
 你清除浏览器缓存再试试看
