### ISSUE TITLE
墙裂建议加入数学公式支持 hexo-math

### ISSUE THREAD

**Issue by daniel18qzx** [XPoet/hexo-theme-keep#81]

**Comment by XPoet** [comment]
可以使用  hexo-filter-mathjax

查看配置文档：
https://keep-docs.xpoet.cn/usage-tutorial/advanced.html#%E6%95%B0%E5%AD%A6%E5%85%AC%E5%BC%8F

**Comment by daniel18qzx** [comment]
感谢！另外补充这则教程，也成功能在keep上使用：

https://www.jianshu.com/p/7ab21c7f0674
