### ISSUE TITLE
_config.keep.yml节点数据读取

### ISSUE THREAD

**Issue by MrSeaning** [XPoet/hexo-theme-keep#82]
custom_label_list节点的数据 没有读取hexo目录下_config.keep.yml 文件中的内容，读取的是node_modules主题目录下配置文件的内容，其他配置项可以读取_config.keep.yml文件中的，我是使用npm的方式安装的主题，最新版3.4.2，求助大家是我哪里配置的有问题吗？ 拜谢

**Comment by MrSeaning** [comment]
使用平滑升级  _data/keep.yml 倒是可以解决

**Comment by XPoet** [comment]
你的主题配置文件 _config.keep.yml 发一份我看看，其他配置项能读取，那 custom_label_list 也是能读取的

**Comment by XPoet** [comment]
使用 npm 安装 Keep 主题，作者建议采用平滑升级的方法来存放主题配置文件 `_data/keep.yml`

**Comment by MrSeaning** [comment]
@XPoet  _config.keep.yml直接复制主题的 _config.yml文件，改了个名字

**Comment by XPoet** [comment]
那就采用在 `_data` 存在主题配置文件
