### ISSUE TITLE
移动设备文章页面没有分类和标签显示

### ISSUE THREAD

**Issue by MapleNe** [XPoet/hexo-theme-keep#84]
请问是否能在移动设备的文章页面添加分类和标签显示？

**Comment by XPoet** [comment]
Keep 是个响应式主题，在手机端，为了界面美观，在文章页头部隐藏了分类和标签。你可以改源码来显示。
下个版本，我考虑在文章页尾部，增加上分类和标签

**Comment by MapleNe** [comment]
> Keep 是个响应式主题，在手机端，为了界面美观，在文章页头部隐藏了分类和标签。你可以改源码来显示。
> 下个版本，我考虑在文章页尾部，增加上分类和标签

也许可以加个开关来控制是否在手机端显示

**Comment by MapleNe** [comment]
顺便问下代码没有高亮是因为不支持吗？我写的是
`
```shell
```
`

**Comment by XPoet** [comment]
支持代码高亮，请使用正确的 Markdown 格式就会显示代码高亮了

**Comment by XPoet** [comment]
`v3.4.4` 已支持，请使用最新版本
