### ISSUE TITLE
建议添加代码块折叠功能

### ISSUE THREAD

**Issue by Tang0770** [XPoet/hexo-theme-keep#85]
可以增加一个代码块折叠功能吗，或者进一步文章也可以折叠？

**Comment by XPoet** [comment]
可以，这个需求已在主题升级的计划中

**Comment by XPoet** [comment]
keep `v3.4.8` 已支持该功能，请使用最新版本。

<img width="883" alt="image" src="https://user-images.githubusercontent.com/24516169/193205372-b1912b6d-1f5c-4821-a23c-aafbd05e518f.png">

**Comment by Tang0770** [comment]
请问更新keep后是否需要额外进行配置？
更新后在yml文件中修改**code_copy**为**code_block_tools**会报错，不修改**code_copy**则仍然是旧版样式。是我漏看了什么吗？

**Comment by XPoet** [comment]
你是通过哪种方式升级 Keep 主题的?

**Comment by XPoet** [comment]
提供下你的主题配置文件
