### ISSUE TITLE
请问如何放置社交平台的微信二维码连接

### ISSUE THREAD

**Issue by Liar1zhuang** [XPoet/hexo-theme-keep#86]
将二维转成url的方式会跳转到微信下载页面，好像被微信封了，有什么解决方案吗

**Comment by Liar1zhuang** [comment]
另外社交平台的icon只能在Font Awesome中挑选吗，可以通过设置文件目录的形式自定义吗

**Comment by XPoet** [comment]
第一个问题：
你将微信二维码的图片保存下来，上传到图床，把图片外链放到主题配置文件中即可。点击微信图标时，就会跳转到二维码图片的页面。我的网站就是这样实现的 https://xpoet.cn/

![image](https://user-images.githubusercontent.com/24516169/114676801-44097080-9d3c-11eb-9754-d4c57a0deea3.png)

**至于图床，你可以使用作者写的 PicX 图床神器**
**https://github.com/XPoet/picx**

**Comment by XPoet** [comment]
第二个问题：
第三方社交的图片目前只能从 Font Awesome 中挑选，当然你也可以改主题源码来实现自定义

社交图标配置方法：
https://keep-docs.xpoet.cn/usage-tutorial/configuration-guide.html#social-contact

**Comment by Liar1zhuang** [comment]
好的 谢谢您的keep主题和解答。等我先配置好所有的基础功能后再去看一下源代码

发件人: 指间的诗意 ***@***.***>
发送时间: 2021年4月14日 16:20
收件人: XPoet/hexo-theme-keep ***@***.***>
抄送: Liar1zhuang ***@***.***>; Author ***@***.***>
主题: Re: [XPoet/hexo-theme-keep] 请问如何放置社交平台的微信二维码连接 (#86)


第二个问题：
第三方社交的图片目前只能从 Font Awesome 中挑选，当然你也可以改主题源码来实现自定义

社交图标配置方法：
https://keep-docs.xpoet.cn/usage-tutorial/configuration-guide.html#social-contact
