### ISSUE TITLE
为什么按文档来，这里却不行呢

### ISSUE THREAD

**Issue by GSYGSH** [XPoet/hexo-theme-keep#88]
![image](https://user-images.githubusercontent.com/67682211/115069544-49c2aa00-9f26-11eb-8a81-1b901a44a5ab.png)
![image](https://user-images.githubusercontent.com/67682211/115069659-7971b200-9f26-11eb-8a25-dd8765f72074.png)

**Comment by GSYGSH** [comment]
test有写内容也不行

**Comment by GSYGSH** [comment]
我也安装了 npm install hexo-wordcount，但是字数和阅读时长还是不显示

**Comment by XPoet** [comment]
1. 请确保是在你的 Hexo 项目根目录下 `npm install hexo-wordcount`
2. 请确保 hexo-wordcount 成功安装   
   ![image](https://user-images.githubusercontent.com/24516169/115095492-1eef4a80-9f54-11eb-9191-f3bc6fe95c24.png)
3. 如果前两步成功，请清空你的浏览器缓存，刷新一下再查看
4. 你修改了主题配置文件，需要关闭上一次的服务，重新  `hexo s -o` 才能看到效果

**Comment by GSYGSH** [comment]
> 1. 请确保是在你的 Hexo 项目根目录下 `npm install hexo-wordcount`
> 2. 请确保 hexo-wordcount 成功安装
>    ![image](https://user-images.githubusercontent.com/24516169/115095492-1eef4a80-9f54-11eb-9191-f3bc6fe95c24.png)
> 3. 如果前两步成功，请清空你的浏览器缓存，刷新一下再查看
> 4. 你修改了主题配置文件，需要关闭上一次的服务，重新  `hexo s -o` 才能看到效果

可以了，可能是没及时更新的问题吧，还有个问题就是svg格式图片是不是edge浏览器和微信内置浏览器都显示不出来，我用chrome就正常显示

**Comment by XPoet** [comment]
Edge 浏览器和微信内置浏览器都使用了 Chrome 内核，都能能正常显示图片，如果有问题，刷新一下，或者升级浏览器
