### ISSUE TITLE
开启 pjax ，点击搜索结果项，跳转到文章时没有使用 pjax

### ISSUE THREAD

**Issue by TildenJ** [XPoet/hexo-theme-keep#90]
作者大大好 :smile:。我发现同时开启 pjax 和文章搜索功能后，点击搜索，输入关键词。点击结果项，loading bar 不是彩色的，观察控制台也发现页面刷新了。

**Comment by XPoet** [comment]
感谢反馈，我抽空排查下

**Comment by TildenJ** [comment]
您好，刚刚看了一下，`/source/js/local-search.js` 的这一行：

https://github.com/XPoet/hexo-theme-keep/blob/0f9c8607aa6c1c97dba081bf035de89d455c1e78/source/js/local-search.js#L210

用到了 `window.pjax` 的 `refresh()`。而 `/layout/_partial/pjax/pjax.ejs` 里 pjax 没有赋给 window：

https://github.com/XPoet/hexo-theme-keep/blob/0f9c8607aa6c1c97dba081bf035de89d455c1e78/layout/_partial/pjax/pjax.ejs#L4

把这里改成：
```javascript
window.pjax = new Pjax({
```
好像就可以了。

**Comment by XPoet** [comment]
@TildenJ 👍 真是太细心了，小伙伴可不可以帮忙提个 PR，我来合并

**Comment by TildenJ** [comment]
@XPoet 好耶，提交了。

**Comment by XPoet** [comment]
多谢小伙伴 Thanks♪(･ω･)ﾉ
