### ISSUE TITLE
插件跳转失败

### ISSUE THREAD

**Issue by Lovzi** [XPoet/hexo-theme-keep#95]
![image](https://user-images.githubusercontent.com/42086982/117643374-e80afe00-b1ba-11eb-8318-e490b0552dcc.png)
这个点问题是插件跳转失败

**Comment by XPoet** [comment]
小伙伴把问题描述详细一点，使用了什么插件？在什么场景下？怎么操作导致跳转失败

描述详细点，我才能复现场景
